{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "import findspark\n",
    "findspark.init()\n",
    "import pyspark as ps\n",
    "from pyspark.sql import SQLContext\n",
    "from pyspark.ml.feature import HashingTF, IDF, Tokenizer\n",
    "from pyspark.ml.feature import StringIndexer\n",
    "from pyspark.ml import Pipeline\n",
    "from pyspark.mllib.clustering import LDA, LDAModel\n",
    "from pyspark.mllib.linalg import Vectors\n",
    "from pyspark.ml.feature import CountVectorizer, CountVectorizerModel, Tokenizer, RegexTokenizer, StopWordsRemover\n",
    "from pyspark.sql import functions as F\n",
    "import warnings"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Make Spark Context and SQL context"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: SparkContext already exists in this scope\n",
      "  \n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    # create SparkContext on all CPUs available: in my case I have 4 CPUs on my laptop\n",
    "    sc = ps.SparkContext('local[4]')\n",
    "    print(\"Just created a SparkContext\")\n",
    "except ValueError:\n",
    "    warnings.warn(\"SparkContext already exists in this scope\")\n",
    "    sqlContext = SQLContext(sc)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Load from CSV and preview data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pyspark.sql.dataframe.DataFrame'>\n",
      "+---+----------+--------------------+--------+---------------+--------------------+\n",
      "|_c0|       _c1|                 _c2|     _c3|            _c4|                 _c5|\n",
      "+---+----------+--------------------+--------+---------------+--------------------+\n",
      "|  0|1467810369|Mon Apr 06 22:19:...|NO_QUERY|_TheSpecialOne_|@switchfoot http:...|\n",
      "|  0|1467810672|Mon Apr 06 22:19:...|NO_QUERY|  scotthamilton|is upset that he ...|\n",
      "|  0|1467810917|Mon Apr 06 22:19:...|NO_QUERY|       mattycus|@Kenichan I dived...|\n",
      "|  0|1467811184|Mon Apr 06 22:19:...|NO_QUERY|        ElleCTF|my whole body fee...|\n",
      "|  0|1467811193|Mon Apr 06 22:19:...|NO_QUERY|         Karoli|@nationwideclass ...|\n",
      "+---+----------+--------------------+--------+---------------+--------------------+\n",
      "only showing top 5 rows\n",
      "\n"
     ]
    }
   ],
   "source": [
    "df = sqlContext.read.format('com.databricks.spark.csv').options(header='false').load('sentiment140dataset/training.1600000.processed.noemoticon.csv')\n",
    "print(type(df))\n",
    "df.show(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Clear out useless data and rename useful columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+----------+--------------------+---------------+--------------------+\n",
      "|  tweet_id|                date|       username|               tweet|\n",
      "+----------+--------------------+---------------+--------------------+\n",
      "|1467810369|Mon Apr 06 22:19:...|_TheSpecialOne_|@switchfoot http:...|\n",
      "|1467810672|Mon Apr 06 22:19:...|  scotthamilton|is upset that he ...|\n",
      "|1467810917|Mon Apr 06 22:19:...|       mattycus|@Kenichan I dived...|\n",
      "|1467811184|Mon Apr 06 22:19:...|        ElleCTF|my whole body fee...|\n",
      "|1467811193|Mon Apr 06 22:19:...|         Karoli|@nationwideclass ...|\n",
      "+----------+--------------------+---------------+--------------------+\n",
      "only showing top 5 rows\n",
      "\n"
     ]
    }
   ],
   "source": [
    "columns_to_drop = ['_c0', '_c3']\n",
    "df = df.drop(*columns_to_drop)\n",
    "df = df.withColumnRenamed('_c1', 'tweet_id').withColumnRenamed('_c2', 'date').withColumnRenamed('_c4', 'username').withColumnRenamed('_c5', 'tweet')\n",
    "df.show(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Check that there are no NA values (there shouldn't be any)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "before dropping na 1600000\n",
      "after dropping na 1600000\n"
     ]
    }
   ],
   "source": [
    "print(f\"before dropping na {df.count()}\")\n",
    "df.dropna()\n",
    "print(f\"after dropping na {df.count()}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Check tweet frequency over date"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Convert date column from String to Timestamp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[('tweet_id', 'string'), ('date', 'string'), ('username', 'string'), ('tweet', 'string')]\n",
      "+--------------------+\n",
      "|                date|\n",
      "+--------------------+\n",
      "|Mon Apr 06 22:19:...|\n",
      "|Mon Apr 06 22:19:...|\n",
      "|Mon Apr 06 22:19:...|\n",
      "|Mon Apr 06 22:19:...|\n",
      "|Mon Apr 06 22:19:...|\n",
      "+--------------------+\n",
      "only showing top 5 rows\n",
      "\n",
      "None\n",
      "+----------+-------------------+---------------+--------------------+\n",
      "|  tweet_id|               date|       username|               tweet|\n",
      "+----------+-------------------+---------------+--------------------+\n",
      "|1467810369|2009-04-07 01:19:45|_TheSpecialOne_|@switchfoot http:...|\n",
      "|1467810672|2009-04-07 01:19:49|  scotthamilton|is upset that he ...|\n",
      "|1467810917|2009-04-07 01:19:53|       mattycus|@Kenichan I dived...|\n",
      "|1467811184|2009-04-07 01:19:57|        ElleCTF|my whole body fee...|\n",
      "|1467811193|2009-04-07 01:19:57|         Karoli|@nationwideclass ...|\n",
      "+----------+-------------------+---------------+--------------------+\n",
      "only showing top 5 rows\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(df.dtypes)\n",
    "print(df.select('date').show(5))\n",
    "form = 'EEE MMM dd H:m:s z yyyy'\n",
    "df2 = df.withColumn('date', F.unix_timestamp('date', form).cast('timestamp'))\n",
    "df2.show(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Now that we know df2 is correct, make df = df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Make linegraph of tweets over time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "+------------+------+\n",
      "|no_timestamp| count|\n",
      "+------------+------+\n",
      "|  2009-04-07| 20671|\n",
      "|  2009-04-17|   499|\n",
      "|  2009-04-18| 18327|\n",
      "|  2009-04-19| 31148|\n",
      "|  2009-04-20| 18275|\n",
      "|  2009-04-21| 11105|\n",
      "|  2009-05-01|  1706|\n",
      "|  2009-05-02| 29390|\n",
      "|  2009-05-03| 33363|\n",
      "|  2009-05-04| 21505|\n",
      "|  2009-05-09|  5755|\n",
      "|  2009-05-10| 31177|\n",
      "|  2009-05-11|   836|\n",
      "|  2009-05-12|  4186|\n",
      "|  2009-05-13|   529|\n",
      "|  2009-05-14| 20997|\n",
      "|  2009-05-16|  3496|\n",
      "|  2009-05-17| 39441|\n",
      "|  2009-05-18| 42832|\n",
      "|  2009-05-22| 41206|\n",
      "|  2009-05-23|   169|\n",
      "|  2009-05-25|   169|\n",
      "|  2009-05-27| 11619|\n",
      "|  2009-05-28|  2019|\n",
      "|  2009-05-29| 76020|\n",
      "|  2009-05-30|101619|\n",
      "|  2009-05-31|104088|\n",
      "|  2009-06-01|100462|\n",
      "|  2009-06-02| 66799|\n",
      "|  2009-06-03| 53054|\n",
      "|  2009-06-04|  4638|\n",
      "|  2009-06-05| 48541|\n",
      "|  2009-06-06|111056|\n",
      "|  2009-06-07|109279|\n",
      "|  2009-06-08|  1111|\n",
      "|  2009-06-14|   500|\n",
      "|  2009-06-15|103138|\n",
      "|  2009-06-16| 76266|\n",
      "|  2009-06-17| 44060|\n",
      "|  2009-06-18| 43061|\n",
      "|  2009-06-19| 43264|\n",
      "|  2009-06-20| 45335|\n",
      "|  2009-06-21| 22285|\n",
      "|  2009-06-22| 12009|\n",
      "|  2009-06-23| 16643|\n",
      "|  2009-06-24|   458|\n",
      "|  2009-06-25| 25894|\n",
      "+------------+------+\n",
      "\n",
      "None\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "<matplotlib.axes._subplots.AxesSubplot at 0x1104214e0>"
      ]
     },
     "execution_count": 66,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAY0AAAELCAYAAAAlTtoUAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvOIA7rQAAIABJREFUeJzsvXecXPV99/v+TZ/Z3qUt0qqBGhJlEQLcQBjkKuzYMZgArtzE9uPkcXIf28njy41LEjtPbAdf2wm2weA4Jm6hJJhimm1AIIkmCUlotdJKuyttb7M7fX73j3PO7OxqZqedaavf+/Xal2bOnLZHs+dzvl1IKVEoFAqFIh0sxT4BhUKhUJQPSjQUCoVCkTZKNBQKhUKRNko0FAqFQpE2SjQUCoVCkTZKNBQKhUKRNko0FAqFQpE2SjQUCoVCkTZKNBQKhUKRNrZin4DZNDY2ys7OzmKfhkKhUJQV+/btG5FSNqVab8mJRmdnJ3v37i32aSgUCkVZIYToTWc95Z5SKBQKRdoo0VAoFApF2ijRUCgUCkXaLLmYhkKhUKQiFArR19eH3+8v9qkUHJfLRXt7O3a7PavtlWgoFIpzjr6+Pqqqqujs7EQIUezTKRhSSkZHR+nr62PVqlVZ7UO5pxQKxTmH3++noaHhnBIMACEEDQ0NOVlYSjQUCsU5ybkmGAa5/t5KNBQKRcHY3TPKsWFvsU9DkQNKNBQKRUHwhyLc9MMX2PFPz3DrXS/yzBvDSCmLfVpLkm9/+9vMzs7mZd9KNBQKRUGY9IWIRCWXr27g9dNT3HrXi1zzzWf4t929zAbDxT69JYUSDYVCUfZM+kIAfPiyFTz7+av51oe24nHY+N/3H2D73z3B3z98iMGpcycF9t5772XLli1s3bqVm2++mRMnTnD11VezZcsWduzYwcmTJwH4yEc+wi9/+cvYdpWVlQA8/fTTvO1tb+MDH/gA69ev56abbkJKyR133MHAwABXXXUVV111lennrVJuFQpFQTBEo9ptx2Gz8L6L2rn+wjb29Y5z97Mn+MHve3j99BQ/+fhlBT2vv33oIK8PTJm6z42t1dz+nk1JPz948CBf/epXee6552hsbGRsbIxbb7019nPXXXfx2c9+lvvvv3/R47z88sscPHiQ1tZWrrzySp599lk++9nP8s1vfpOnnnqKxsZGU38vUJaGQqEoEFO6aNS454rKhBB0ddbz3Zsu5q3nNTExGyrW6RWUJ598kg9+8IOxm3p9fT3PP/88H/7whwG4+eab+cMf/pByP9u2baO9vR2LxcKFF17IiRMn8nnagLI0FApFgZhMIBrxuB1W/KFIIU8JYFGLoBSw2WxEo1EAotEowWAw9pnT6Yy9tlqthMP5jw0pS0OhUBSEVKLhslnxFUE0isHVV1/NL37xC0ZHRwEYGxvjiiuu4L777gPgpz/9KW9+85sBbdzDvn37AHjwwQcJhVJbY1VVVUxPT+fl3JWloVAoCsKUT3sKrnIlvu24imRpFINNmzbxN3/zN7z1rW/FarVy0UUX8Z3vfIePfvSj/OM//iNNTU3cfffdAHzyk59k165dbN26lZ07d1JRUZFy/7fddhs7d+6ktbWVp556ytRzF0stT7qrq0uqIUwKRenx5Yde5z/2nOTgl3cm/Pwr//U6/7HnFAf+9rq8n8uhQ4fYsGFD3o9TqiT6/YUQ+6SUXam2Ve4phUJRECZ9oaSuKQCX3YIvFFEFfyWOEg2FQlEQJn0hqhcRDbfdSiQqCUWUaJQySjQUCkVBmPIvLhouuxUAf7gwcY1z1aLJ9fdWoqFQlCkH+if54L88x/u+9yxD06VfST2V0j2li0Yw/6LhcrkYHR0954TDmKfhcrmy3ofKnlIoyoxJX4hvPnaEn+zupc7jwBeK8P7vPcc9H9vGmqbKYp9eUiZ9ITancE8BpqfdnhqbpdZjp8o1d+z29nb6+voYHh429VjlgDG5L1uUaCgUZYKUkv98uZ+/e/gwYzMB/mT7Sv7y2vPpHZ3hYz/ewx99/zl+dGsXl6ysL/apJmTKF6LatYhoOHRLIxQ19bg3/fAFrjq/ib/dtTm2zG63Zz257lxHuacUijLgyJlpPnTnbj7381dpr3Pz4GfexJd3babGbWdLey2//rMrqfM4+PAPXuDRg2eKfbpnEYpEmQlGUmZPgfmWxog3wKHT+Sl0OxdJKRpCiLuEEENCiANxy+qFEI8LIY7q/9bpy4UQ4g4hRLcQ4jUhxMVx29yqr39UCHFr3PJLhBD79W3uEPpYqWTHUCjONb7zxFHeecfveWNwmn94/wX8+s+uYHNbzbx1VjR4+OWfXs6G5dX82b/t4yfPnyjKuSZjru9UcudGLKZhomhIKfGFIvSMqMFPZpGOpfFjYGE1zheAJ6SU64An9PcA7wDW6T+3Ad8HTQCA24HLgG3A7XEi8H3gk3Hb7UxxDIXinGE2GOafHn+Dt57XxFN/+TZu2LYCiyXxuM6GSic/++R2rl7fwpceOMjXHzlcMoHeWAsRT2FjGoFwFClhxBuMnYMiN1KKhpTyd8DYgsW7gHv01/cA18ctv1dq7AZqhRDLgeuAx6WUY1LKceBxYKf+WbWUcrfUvt33LthXomMoFOcMPcMzAHzgknbqKhwp13c7rPzLn1zMhy9bwfefPsb//cvXSkI4pvxaC5HFYhr5yJ6Kt1p61JhZU8g2ptEipTytvz4DtOiv24BTcev16csWW96XYPlix1Aozhm6h7Qb3drm9LOibFYLX7t+Mx+9spNf7uujb9yXr9NLm1TNCmHO0jCzTsM3TzRmTNvvuUzOgXDdQsjro0yqYwghbhNC7BVC7D0XU+gUS5fuIS9Wi2Blgyej7YQQ7FivPWf1T5SJaOjZU76gedlTvjirRcU1zCFb0RjUXUvo/w7py/uBjrj12vVliy1vT7B8sWOchZTyTilll5Syq6mpKctfSaEoPbqHvKyo9+C0WTPetq3ODUB/CVgaU3FT+5Lhspkf05gNKkvDbLIVjQcBIwPqVuCBuOW36FlU24FJ3cX0KHCtEKJOD4BfCzyqfzYlhNiuZ03dsmBfiY6hUJwzdA97sy7YW16jVf2Wi3vK5dBuR2ZmTxn7ctutHB9RomEG6aTc/gx4HjhfCNEnhPg48A/A24UQR4Fr9PcADwM9QDfwA+BTAFLKMeArwB7958v6MvR1fqhvcwz4jb482TEUinOCUCTKiZGZjOIZ8bjsVpqqnPRPzJp8Zpkz5QvhsFliwe5EOKwWLMJc0TCslg3Lqzg+MkM0WvykgHInZUW4lPLGJB/tSLCuBD6dZD93AXclWL4X2Jxg+WiiYygU5wonx2YJR2XWogHQVusumZjGYlYGaHEYl906Lw6RK8a+NrXW8NLJCfonfHTUZxYfUsxHVYQrFCVKNplTC2mrc5dGTMMfojrJxL543HZrXrKnNrVWA9CjXFQ5o0RDoShRDNFY05R6vGcy2mvdDEz4i+6WScfSAHRLw/zsqY2GaKhajZxRoqFQlCjHhry0VDvndWfNlLY6N8FIlBFvwMQzy5z0RcOSl5hGe52HKpdNZVCZgBINhaJE6R725uSaAi2mAdBX5LhGqql9Bm6HNS+i4XFYWd1UqWo1TECJhkJRgkgpOTbkZW2O8zHa67Sgb7HjGlO+cFqWhttuNbVOwx+MIAQ4bRbWNFYoS8MElGgoFCXImSk/M8FI7paGUeBXREsjGpVM+TOIaZhsabjtVoQQrG6q4PSkn9lg2LT9n4so0VAoSpBYEDxH0ah02qhx24tqaUwHwki5eGGfgctuNXUI02wwEutptVq32pS1kRtKNBSKEsSMdFuDYtdqxFqIpBHQd9vNj2m4YqKhZaGpyvDcUKKhUJQg3UNeql02miqdOe+r2LUak2n0nTJw2S2mFvf5Q5FYI8TOhgqEUJZGrijRUChKkO4hL2uaK9EHWeaEYWkUa67GVBp9pwxML+6Lc0+57Fbaat0qgypHlGgoFCXIseGZnDOnDNrr3HgDYaZ8xQkAp9Os0MDlMLmNSJylAbBKZVDljBINhaLEmJwNMeINmBLPgPhajeI0LpzyG+6p1G1EXDYrgXDUtAp2XygaszQA1jRV0jPsLYlphuWKEg2FosToHp4GzAmCQ/HnamRiaRhWQSBsTgaVLxieJxqrmyqYCUYYmi5uhXw5o0RDoSgxzMycgjlLo1gZVJO+EBahpf+mwrjBm1WrsdA9tbpRu6bHVA+qrFGioVCUGN1DXhw2S6yaO1fqKxy47JaiWRpTvjDVbntaQX2XXbslmSYawei8GR5G2q2Ka2SPEg2FosToHvKyurECqyX3zCnQ5lQUs1Yj3WaFQOwGb1athj8UwRNnaSyrduG2W5Vo5IASDYWixDg2PJNzJfhC2uo8ZSEaMfeUCRlUUspYGxEDi0VoGVQq7TZrlGgoFCWEPxTh1Pisaem2Bm21xSvwK5alEYxEiUTlvJgGaC4qVRWePUo0FIoSomd4BinNC4IbtNe5GZ0JmloDkS7a1L40LQ2HIRq5Z0/59WFOC+eSr26q5NTYLAETiwjPJZRoKBQlRPewuZlTBnMZVIWv1ZhKc5YGaHUaYE4g3NiHe4ForGmqICrh5Ghx6lbKHSUaCkUJ0T3kRQitctlMjFqNvgK7qKSUmcU0HOZlT8VEwzH/Nmdc22MqGJ4VSjQUihLi2JCXjjrPWS6VXClWrYY/FCUUkWlVg4O5MQ3DFee2zz+2IRoqGJ4dSjQUihLimAkjXhPRUu3CZhEFD4ZnUg0OJotGzNKYL8BVLjvNVU6VdpslSjQUihIhEpX0jMzkRTSsFsGyGlfBLY1MRcPMlNs5S+Nsq211UwU9qio8K5RoKBQlwqmxWYLhqOnptgbFSLvN3tLIPXsqWSActAyqHpV2mxVKNBSKEsGsEa/JaKsrfFV4JlP7QLOIHFZLXgPhAKsbK5iYDTE2E8z5OOcaSjQUihIhlm6bJ0ujvdbN4JSfUMS8GdypyNTSAK3/lBkxDb/hnnKcHYRfE5sXrlxUmZKTaAgh/qcQ4qAQ4oAQ4mdCCJcQYpUQ4gUhRLcQ4j+EEA59Xaf+vlv/vDNuP1/Ulx8RQlwXt3ynvqxbCPGFXM5VoSh1jg15aax0UuNJ/wabCW11bqISzkz687L/RGQjGm6HOXPCF3dPGRlUykWVKVmLhhCiDfgs0CWl3AxYgRuArwPfklKuBcaBj+ubfBwY15d/S18PIcRGfbtNwE7ge0IIqxDCCnwXeAewEbhRX1ehWJJ0D3tZ22xufUY8bbVa19xC1moYA5iqXOml3IIW1zDDPTW7SCC8vc6D3SpUBlUW5OqesgFuIYQN8ACngauBX+qf3wNcr7/epb9H/3yH0Hol7wLuk1IGpJTHgW5gm/7TLaXskVIGgfv0dRWKJYeUku6h/KTbGsSGMRUwrjHpC1HptGGzpn+rcdvNGflqCI/TdvaxrRbBygaVQZUNWYuGlLIf+D/ASTSxmAT2ARNSSmMYcR/Qpr9uA07p24b19Rvily/YJtlyhWLJMTwdYNofzls8A6C11gUUdoJfJtXgBi67Fb8Jk/v8oQguuwVLkhbzqxsrlHsqC3JxT9WhPfmvAlqBCjT3UsERQtwmhNgrhNg7PDxcjFNQKHJiblpfVd6O4bRZaa5yFrT/VCZ9pwxcdkssiJ0LvmAET4IguMHqpkp6R2cIFzAxYCmQi3vqGuC4lHJYShkCfg1cCdTq7iqAdqBff90PdADon9cAo/HLF2yTbPlZSCnvlFJ2SSm7mpqacviVFIrikK9GhQspdNrtlC9MdQbxDNDdUyYFwhPFMwxWN1UQisiC9+Mqd3IRjZPAdiGER49N7ABeB54CPqCvcyvwgP76Qf09+udPSimlvvwGPbtqFbAOeBHYA6zTs7EcaMHyB3M4X4WiZDk25KXSaaOl2pnX4xS6wC8b95Rp2VPBSGx8bCLWNKkeVNmQS0zjBbSA9kvAfn1fdwKfBz4nhOhGi1n8SN/kR0CDvvxzwBf0/RwEfo4mOI8An5ZSRvS4x2eAR4FDwM/1dRWKJUf3sJc1TRVpzdHOhbY6NwMTfqJRmdfjGGQV07CZaGk4FrE0Go1aDRXXyITM7MYFSClvB25fsLgHLfNp4bp+4INJ9vM14GsJlj8MPJzLOSoU5UD3kJcr1zbm/TjttW6CkSgj3gDN1a68Hy8r0TDR0ljMPVVX4aDOY1ct0jNEVYQrFEVmyh9icCqQ93gGxM3VKEBcIxiO4gtFMg6Eu+1W03pPpWoxv7qpUqXdZogSDYWiyBzXn3TX5DHd1sAo8CtEXMMo7Ms85VbrPaWFPLPHH4rgWcQ9BdpsjROjytLIBCUaCkWRMZrmNVflNwgOhS3wy6aFCGiWRiQqCUVyE41U2VMAHXUeBqcCal54BijRUCiKzHRAq4XNpNVGtlQ6bdS47YWxNLIUjVh79Bxv5LPBxQPhAO2GiKq027RRoqFQFBmv3xCN/DQqXEhbbWFqNQxLI91RrwYx0cixwM8fTB3T6KgvfD+uckeJhkJRZLwB7eZa6cy/pQF6gV8BbpK5uKeAnNNu03FPGZbGqfHCVcmXO0o0FIoiM+0PIwQpg7Zm0Vbrpm98NudAcypiA5iyKO6D3Kb3hSJRwlGZ8pq2VLuwW4WyNDJAiYZCUWSm/WEqnba8F/YZtNe5mQlGYpZAvpjS3W7pTu0zMKq4c7E0jG1TuaesFkFrrVuJRgYo0VAoiow3EKaqQK4p0CwNyL8ff9IXwmmzpLxxL8RYP5f26L7Y1L7Ux+6o83BqTLmn0kWJhkJRZLz+MJUFyJwyKFTa7eRs5tXgMBfTyCV7yrfIAKaFtNcpSyMTlGgoFEXGGwgXLAgOc5ZGvoPhU/7sRMOM7KnFRr0upKPew4g3YMrgp3MBJRoKRZGZDoSpLFC6LUB9hQOX3ZJ/SyOLWRpgTvZUTDTScE/FajUKOGeknFGioVAUGa8/VJDCPgMhREFapGfTrBDMyZ7yZ+Se0mo1To0pF1U6KNFQKIpMoQPhAG11noJYGlm5p2yFtTQ6jCaOqlYjLZRoKBRFxki5LSSFqAqf8oUyntoH4HJot6Vc2qPPZmBpNFY6cdgsnFLB8LRQoqFQFJFIVDIbjBQ0ewo0P/7YTJDZYDgv+49GJdOBcFaWhsNqwSJyE4106zQALBahZ1ApSyMdlGgoFEXEqzcrLIalATCQJ2tj2h9GysyrwUGLubjs1pyymfwZuKdAi2uomEZ6KNFQKIqIt4AdbuOJDWPKk0sm21kaBm57biNfDcFJtzVLh7I00kaJhkJRRIwOt5XOwqXcAqxurADgQP9kXvY/mWXfKQNXjtP7Yu4pW/qWxvhsKCbiiuQo0VAoikisw22BLY2GSidb22t48vBQXvafbYdbA5fdkltMIxjBabNgsaTXz6ujXmVQpYsSDYWiiEz7i+OeArh6fQsvn5pg1Bswfd+5iobbkaN7KpR6AFM8Rq1Gn4prpESJhkJRRGIxjQIHwgF2bGhGSnj6yLDp+852ap+B227N2dJIJ93WoEPN1UgbJRoKRRExLI1Cu6cANrVW01LtzIuLyoyYRiEtjfoKB267VTUuTAMlGgpFEZkLhBdeNIQQXL2+md+9MUwwnH3QORGTvhBWi6Aiy8FSuQbC/WlM7YtHCEFHvVu1SE8DJRoKRRGZ1t1TFY7CiwZocY3pQJi9J8ZM3a/RQiTbwVK5uqdmM3RPgRbXUJZGapRoKBRFxKu3EEk3y8dsrlzbgMNm4QmTXVRT/nBWLUQMXHZLbkOYMnRPgVYlr2IaqVGioVAUEW8gVBTXlIHHYeOKNQ2mxzWybVZo4LZbcx7ClOnEwI46D9P+cN7H4JY7OYmGEKJWCPFLIcRhIcQhIcTlQoh6IcTjQoij+r91+rpCCHGHEKJbCPGaEOLiuP3cqq9/VAhxa9zyS4QQ+/Vt7hCFGqKsUBQIb6CwU/sSsWN9M8dHZugZ9pq2z2xnaRiY0UYk3WpwA2OuhoprLE6ulsY/A49IKdcDW4FDwBeAJ6SU64An9PcA7wDW6T+3Ad8HEELUA7cDlwHbgNsNodHX+WTcdjtzPF+FoqSY9oeLUqMRz1XrmwFMtTamc7Q0XHYrgXCUaFRmtb0vw0A4aBP8IP+z08udrEVDCFEDvAX4EYCUMiilnAB2Affoq90DXK+/3gXcKzV2A7VCiOXAdcDjUsoxKeU48DiwU/+sWkq5W0opgXvj9qVQLAmK0RZ9Ie11HtYvq+KJQ+aJRq6WhhGPCGSZ1ZWNe6pdzdVIi1wsjVXAMHC3EOJlIcQPhRAVQIuU8rS+zhmgRX/dBpyK275PX7bY8r4Ey89CCHGbEGKvEGLv8LD5hUoKRb7wBopvaQBcvb6ZPSfGTPHnSylzjmm4bNqtKdtajWwC4TVuO1VOm7I0UpCLaNiAi4HvSykvAmaYc0UBoFsI2dmXGSClvFNK2SWl7Gpqasr34RQK0/CWgKUBWnV4OCr5/dHcH7pmgxHCUZlbINyR/fS+UCRKKCIzdk8JIWhT3W5Tkoto9AF9UsoX9Pe/RBORQd21hP6vYfP2Ax1x27fryxZb3p5guUKxZPAGwgXvcJuICzvqqPPYedIEF5XRFr3alVtMA7IbxBSbpZGhaIAW11BzNRYna9GQUp4BTgkhztcX7QBeBx4EjAyoW4EH9NcPArfoWVTbgUndjfUocK0Qok4PgF8LPKp/NiWE2K5nTd0Sty+FouyJRmVJZE8BWC2Cq85v5qkjQ0SyDD4b5NqsEOZEI5sMqkzmgy/EmOCnOUkUicj12/o/gJ8KIRxAD/BRNCH6uRDi40Av8Mf6ug8D7wS6gVl9XaSUY0KIrwB79PW+LKU0ylM/BfwYcAO/0X8UiiXBTLB4zQoTcfWGZn79cj8vnxynq7M+6/1MzuYuGu5cLI1gdN4+MqGjzsNMMML4bIj6CkfG258L5PRtlVK+AnQl+GhHgnUl8Okk+7kLuCvB8r3A5lzOUaEoVWKjXkvA0gB487ombBbBE4eHchKNKb2flhkxjWz6T82GwvP2kQnxGVRKNBKjKsIViiLhLeIsjUTUuO1c2lmfc1xjrsNtDm1EbNkHwg2XVjaWhjFXQ8U1kqNEQ6EoElNF7HCbjB0bmjkyOJ1TVbQZMQ23I/uU29io12xEQ03wS4kSDYWiSMQGMJWIpQFavQbAU0eytzYM0agqcvZUpm1EQMv4qnHbVePCRVCioVAUiblZGsVPuTVY3VTJqsaKnKrDp3whqlw2rDl07s1FNHxGIDzLWR4d9W5V4LcISjQUiiLhDWhP5KUSCDe4en0zzx8bZUa3hDJlyhfKqUYD5uIROaXcZuGeAmiv9aimhYugREOhKBLTJRjTAK3rbTAS5dnukay2z7WFCMRbGplnT/n0VOZsYhowZ2moWo3EKNFQKIpELOW2xESjq7OeSqeNZ97IrqXIlD930bBaBA6rJadAeLbuqfY6D4FwlBFvMKvtlzpKNBSKIuH1h/E4rDn5/vOBw2ZhVWMF/RPZ+fW1Dre5C6HLbsktppGDpQGoYHgSlGgoFEWiVDrcJqK+wsHYTHZP2ma4p0CzFLISjVAEh82StRgbtRoqGJ4YJRoKRZEohVkayWiodDCapXvGLNFw2a1Zuaf8WQxgikdN8FscJRoKRZGYDoSpzDHLKF80VjoZnQlkHAwOhCP4Q1FzLI0sR77OBsM5iYbHYaOhwqEsjSQo0VAoioTXHyqZZoULqa9w4A9Fmc3wpj3l04L7uUztM3DZrfizmNznC0WzDoIbtKu5GklRoqFQFAltlkZpikaD3qwvUxeVGS1EDFx2C/5s6jSyGPW6kPZ6j7I0kqBEQ6EoEl5/aczSSERDpS4aM4GMtosNYDLLPZVlTCObFiLxtNe56R/3Ec1xtshSRImGQlEkpkva0nAC2VsauVaEQ27ZU7nENECbqxGMRBmazkw0zwWUaCgURUBKWdIpt4alkWnarSEyjZW5z6Jw2bKzNGbNcE/VqVqNZCjRUCiKwGwwgpSl1eE2HsPSGMnQPTWsP5k3VjpzPgdXlpaGPxTJORDeUW/UaijRWIgSDYWiCEyXYIfbeNwOKx6HNWP31PB0gAqHlQoT3G5uuzXL3lMR3Pbcbm1ttfpcDTWM6SyUaCgURaBUO9zGk01V+LA3QFNV7lYGaNlTvlAk41oRXyiCx5HbdXXZrTRXOZV7KgFKNBSKImBYGqVapwHQUOlkxJuZe2pkOmCKawo0SyMSlYQimYtGrjENMGo1zLc0vIEwA1n29SoFlGgoFEUg1uG2hC2NxqJbGnp79HD6cY1IVBIMR3POngItrmGmpTETCPPdp7p509ef5Lpv/Y5gFoWLpYASDYWiCHhLdJZGPPUVmfefGp7Og2hkUOA31xY991tbe52b0xN+wpHcbu6zwTD/+swx3vyNp/jHR49Q73EwHQhzfGQm53MsBqX7jVUoljDTJTpLI56GuP5TQqTuGBsIR5j0hWgy0T0FZJR2a/SqMsXSqPMQjkpu+uELXL6mgctWNXDRitq0XV/+UIR/293LvzxzjBFvkLec18T/vGYdboeVnd/+PYfPTHH+sqqcz7PQlO43VqFYwhiWRqmm3ILWSiQUkUwHwmkV6xlDi8yyNIy02UwyqPwxSyP367pz8zKODnl5/tgo//zEUaQ8isNqYWtHDZetaqCrsw6X3cpMIIw3EGY2GIm9nvKFeei1AYanA1y5toF/ueY8ujrrAQiGo9gsgsNnptmV81kWntL9xioUWTI5G+Lvf3MIu9XCDds62NRaU+xTOotSndoXT6yViDeYnmiYWKMBWvYUZGhp5DgfPJ5aj4MvvXsjoH2n9vaO8cLxMV7oGeX7zxwj8lTyAL3LbuGijjq+c+NFbF/dMO8zh83C2uZKjpyZzvkci0HpfmMViiw4NuzlE/fspW98FiEEP9ndy9b2Gm7ctoL3bG01pX7ADKb9Idx2KzZr6YYV6yuMqvAAqxorUq5vFPaZHdPIpD16zD1lQkwjnhqPnR0bWtixoQXQRP+1vgmQUOG0UeG06v/a8KTx/3r+sir2HB8z9RwLRc5XVghhFUK8LIT4L/39KiHEC0KIbiHEfwghHPpyp/6+W/+8M24fX9T9OaXdAAAgAElEQVSXHxFCXBe3fKe+rFsI8YVcz1WxtPn90WHe991nmfSF+PdPbufFv97B7e/ZiC8U4Qu/3s+2r/2Wv/7P/Rzonyz2qWodbkvYNQVzFkO6s7KHveaKhjuL7CmjlbsZKbeLUem0ccWaRq5Y28jWjlrWNlexvMZNtcue1oPA+cuqGJj0x3p1lRNmyPGfA4fi3n8d+JaUci0wDnxcX/5xYFxf/i19PYQQG4EbgE3ATuB7uhBZge8C7wA2Ajfq6yoU85BScs9zJ/jI3XtYXuPmgU9fyaWd9dR6HHz0ylU8+hdv4Vd/dgXvuGA5v36pj3d/5w/8j5+9XNRznvaHS7pGA+a7p9LBsDQaTOg7BdllT/lNdE/lkw3LqgF4Y7D8XFQ5iYYQoh14F/BD/b0ArgZ+qa9yD3C9/nqX/h798x36+ruA+6SUASnlcaAb2Kb/dEspe6SUQeA+fV2FIkYoEuV/33+A2x88yFXnN/OrT10R6xtkIITgkpV1/J8PbuWFv76GazY087s3hot0xhrlYGnEu6fSYXg6QK3HjtNmzg07q+ypWCC8tEXDyJo6fHqqyGeSOblaGt8G/hdgpDc0ABNSyrD+vg9o01+3AacA9M8n9fVjyxdsk2y5QgHA+EyQW370Ij994SR/9rY13HnzJSkDyzVuOxd21DLpC2XVDM8svCU8H9zAabNS5bSl7Z4a8QZMS7eF7LKnjJiGx17a13Z5jYsql43DZRgMz1o0hBDvBoaklPtMPJ9sz+U2IcReIcTe4eHiPkEqCoM3EOZ933uWfb3jfPOPt/L5neuxWFLXEgA0V7mAOXdKMSjlqX3x1FemXxU+bGILEdBao0N2lobL5EC42Qgh2LCs+twSDeBK4L1CiBNorqOrgX8GaoUQxl9DO9Cvv+4HOgD0z2uA0fjlC7ZJtvwspJR3Sim7pJRdTU1NOfxKinLh1VMTnBid5Zsf2sr7L27PaNvmau3GNjTtz8eppcV0CU/ti6ehwpH29D4zW4jA3I0/E4uwXGIaoLmo3jgznXFDxmKTtWhIKb8opWyXUnaiBbKflFLeBDwFfEBf7VbgAf31g/p79M+flNrVehC4Qc+uWgWsA14E9gDr9Gwsh36MB7M9X8XSwmj4tjmLGgzD0hicKq6lYcZ0u3zTUOnMKBBupmg4rBYsIjPRKFT2lBmcv6yK6UCY/jJrXpgPG+7zwOeEEN1oMYsf6ct/BDToyz8HfAFASnkQ+DnwOvAI8GkpZUSPe3wGeBQtO+vn+roKBacnNSthWY0r421bDEtjqjiWhjG1rxzcU5qlkVo0ZvSKaDNFQwiBy27NrE4jFMFuFdhLuP7FYMNyIxheXi4qU761Usqngaf11z1omU8L1/EDH0yy/deAryVY/jDwsBnnqFhanJ700VjpyOqJss7jwGYRDBYppuELRYhEZXm4p/SYRjQqF40ZGS3UzQyEg+ZmyrT3VDm4pgDOa9FE48jgNNdsbCny2aRP6cuxQpGAgQk/y2vcWW1rsQiaq5wMFck9VQ4dbg3qK5xEopIp/+JFaLExryZaGqC5mTLtPVXq6bYGVS47bbXusguGK9FQlCWnJ30sz8I1ZdBU7SpaINzocFvKzQoNGvVCvVRpt7EWIiZbGi67JaOYhi9UPpYGaC6qcqvVUKKhKEtOT/hprc3O0gCUpZEmDRWaCIymmOBndgsRA7cjM/fUbNCcqX2F4vxlVfSMzBDIoFVKsVGioSg7pv0hpgPhnCyNlmong0WyNMqhw63BXFV4akvDIubWNwuXzZpxym25uKcA1i+rJhKVHBsqn4FMSjQUZYeRObU8J0vDxcRsqChPeLH54GWQchtzT6UQjRFvgIZKJ9Y0CyzTJVNLwxeM4Ckr0dAzqM6Uj4tKiYai7DBqNFpztDSAoriovGUU06gzLI00YhpmVoMbZJNyW04xjc7GChxWS1nN1lCiUWaEIlG++Ov93P7AgWKfStEYmDDH0gAYKkLa7bSeiVQO7im71UKN256yKtzswj4Dl91KIJxB76lQecU07FZtIFM5ZVAp0SgjAuEIn/7pS/zsxZP8ZHdvLDf+XOP0pA+LgJYcblLNRSzwMwLhpTIQKhUNlY6UVeHD0+Y2KzRw2y0ZWRr+MqrTMFi/rEq5pxTm4w9F+NOf7OOx1wf5yBWdRCU8vP90sU+rKAxM+GmucuU09a6YloY3EMZps+CwlcefX6r+U1JKRrzBvFgamRb3zZZZIBy0DKrBqQATs+m1ayk25fGtPcfxBSN84p69PP3GMH/3vgv4f9+7ifNaKnno1YFin1pROD3pY3lt9vEM0G6EVotgsAiWxnQgXBbxDIOGisX7T035wgQj0by5pzKq0yhHS2O5NpCpXFxUSjRSMOUPce23nuGZIg3tmQmE+eiPX+TZYyN844+28OHLVgDwni2t7DkxHgsKm8HHfryH7zxx1LT95YvTk35as6wGN7BYBE2VzuJYGmUwSyOeVO3Rh72a8OYzphGNpu4EG41KAuFo2Vka68tsIJMSjRQ8eWiINwa93PfiyYIfe9of4ta7XmTPiXG+/aEL+WDXXKf4d29tBeC/XzPHRRUMR/ndG8M8e2zElP3lCyklAxO5VYMbtFQ7i2JplMPUvngaKxyMzQaJJLlxG8LbaNKY13hig5jSSI021ik3S6O5ykmtx86RMhn9qkQjBY8cOAPA00eGCzrpbXI2xJ/86EVeOTXBd268iF0Xzh9auKqxggvaanjoNXNcVL2jM4SjklNjpd2meXw2RCAczSlzyqCpylWUQUxef5gqZ+nXaBg0VDqRkqQ+d+MaNufD0rAZMzVSZ1AZAfNyszSEEHowXIlG2eMLRnj6jSHOa6nEF4oUdK70x+7Zw6GBKb7/J5fwzguWJ1znvVtbea1vkhMjuVeTdg95ARiY9BHMIMWx0BjuuLYcYxqgWRpFSbktM0vDqPJO1iJ9ru9U7v8nCzEEIJ1geDnN0ljI+mXVHDkznZYbrtgo0ViE3x0dxh+K8sV3bqDaZePRg4MFOe74TJB9veN8dsda3r5Iy+R3bdHE5L9MsDYM0ZAS+sZnc95fvohVg+cY0wAtg2psJlhwkZz2h6gqo5hGQ6xpYWKBHfEGcVgtVLvN/50MAUgn7bacpvYt5PxlVcwGI/SNl7alD0o0FuXRA2eocdt509pGrtnQwhOHBwlH8n+DOT6qWQ4b9KyKZLTWurm0s46HXs09rtE97I29PjlWyqKh/VHlmj0Fc1XhwwWudym3mIbRtDBZMNwo7BPC3BYiMCca6biGDWuknNqIGJRTOxElGkkIRaL89tAgOzY0Y7dauHbTMiZmQ7x4fCzvxz4+rInGqsaKlOu+Z2srRwanc25D0D3kjX1xS1k0Bib82K2Cxorc/edGgV8hg+FSyrLLnjIsjWRpt8PeQF6C4DBnNaQlGsHytTSMgUzlENdQopGE3T2jTPnD7Ny0DIC3nteEy27hkYNn8n7s4yMzWC2CjnpPynXfsXk5FkFONRvRqOTYsJfL1zTgsls4OVq6onF60seyGteiU+TSJVbgV8D+U4FwlHCZTO0zqPM4EGLxmEY+0m0hLnsqnUC4LiyuMrQ0Kpw2VtR7yqIHlRKNJDx68Axuu5W3nNcEaF/et6xr4rGDg3kPVh0fmWFFvSetOcdNVU6uWNPIQ68NIGV259U/4cMfirKuuYoV9R56S9jSOJ3DxL6FxFqJFLBFeqzDbRlZGlaLoM7jSDpTI5+i4bKlHwgvZ0sDNBfVIeWeKk+iUcljBwd52/lN8zIxrtu0jDNTfl7rn8zr8Y+PzNDZkNrKMHjP1uX0js6yP8vzMuIZa5srWVHv4VQJi8bApC+n7rbxNFRorbwLaWnEZmmUkaUBeiuRBO6pSFQyNpOfvlMAbod2i0pLNMo4EA6aaJwYmSloaj9oYvu5n7+S9vpKNBLw8qkJhqYD7Ny8bN7yHRuasVkEj+bRRSWl5PjIDKsaK9PeZuem5ditImsX1bGheNGo4OTYbNZWSz6JRiWDU35TajRAe4JurHQUNKbhjVka5VOnAVrabaJA+NhMkKjMTzU4nDuBcIDzl1UTlXOZjIXi2LCXX7/Un/b6SjQS8OjBM9itgqvWN89bXutxsH11Q15FY3AqgC8UYVVT6iC4QY3HzlvPa+K/Xjudlevs6KCX+goH9RUOVtS7mQ1GUs6ELgYj3gChiDTN0gAtrlHIWo3pgN4WvcwsjcZKJyMJmhYOx6rBS0A0guUb0wBYv1wLhh8qcDuRTEVKicYCpJQ8evAMV6xppDrBZLXrNrXQMzxD91B+AlY9I9p/4Oo0Mqfiec/WVk5P+tl3cjzjY3YPe1nbrFk2Kxu045ZiBlW/XthnVkwDCt9KZLqM5oPHk8zSyNdscAP3OVKnAdDZUIHTVviBTN1D3owmLirRWMDhM9P0js5y3aZlCT9/+0ZtudFexGxOjGg3684MReOaDS247JaMXVRSSrqH5kTDyNg6OVZ6M4vnxryaZ2kUupVIzD1VZpZGQ6WDidkQoQV1SrFq8Ly7p9LLnrJZRFoJJKWI1SJY11JZ8B5U3UNeVqaRqWlQnlc3jzxy4AxCkLQSe1mNiws7avNWHX58xIvTZmF5dWY3xgqnjR3rW3h4/+mMChBHvEEmfSHWNmmi0V7nRgg4OVp6lalzY17NtTRGC1gVHguEl5ml0aC7n8YXWBtGlXi+3FNWi8BhtaTdRqRcrQyD9cuqOXS6wKIx7GVNc/oxVCUaC3j04Bm6VtYt+uR03aZl7O+fjLlLzEQLgldkVYfwnq3LGfEGeb5nNO1tuuOC4KA92S2rdtFbopaGy26h1mNeENmo1SjUFMRyzp6Cs2s1hqcDVDiseZ1C6LJb0opp+EORso1nGKxfVsWIN5A0vdlsQpEoJ0ZmYn//6aBEI47e0RkOn5lO6poyuG6TZoU8loeAeI8uGtnwtvObqXTaMnJRxafbGnSUaNrt6UkfrTVuU9tVtBS4KnzaH8ZhteC0ldfNLSYa3rNFI1+uKQO3I71BTL5gpGwzpwyM1kEvnZwoyPF6R2cJRyXrCiEaQogOIcRTQojXhRAHhRB/ri+vF0I8LoQ4qv9bpy8XQog7hBDdQojXhBAXx+3rVn39o0KIW+OWXyKE2K9vc4fIR3ObOIysqFSisbqpkvNaKk3PogpHopwam804nmHgslu5dmMLjxw4k7a75diQlwqHdd58ipX1HnpLsCp8YMJvajwDCj/21RsIlZ2VAXGtRBZkUA1PB/LmmjJwpTny1Rcqf/fUpZ31NFQ4+MXeUwU53kJPQzrkYmmEgb+UUm4EtgOfFkJsBL4APCGlXAc8ob8HeAewTv+5Dfg+aCID3A5cBmwDbjeERl/nk3Hb7Ux1UrkUxjxy4AybWqvTat9x3aZlvHh8zFQzsn/CRygis7Y0AK7dtIwpf5hXTqX3pNI9pPkz4/V4Rb2HoelAWhkruXLHE0e5I81pgYalYSYtsarwAomGv7xGvRoYTQvPsjS8BbA07Na0vou+ULQs26LH47BZ+EBXO08cHmKoANbvMd3TsKapAKIhpTwtpXxJfz0NHALagF3APfpq9wDX6693AfdKjd1ArRBiOXAd8LiUckxKOQ48DuzUP6uWUu6WWqXZvXH7Skqy/jipGJry89LJiZRWhsF1m5YRlfDEoaGsjpeIHn0uRqbptvFcvroBi4Dn0pzA1z3kjQXBDVbo1einCtAi/acv9HLPcydSFhOGIlGGpgOmFfYZNFQ6sQgK8gcKeofbMguCA9S47Vgt4ixLY6QAouGyW/GnYTn7guGytzQAbrh0BZGo5Bf7+vJ+rO4hL601roxiUqbENIQQncBFwAtAi5TS6NV9BjDSkNqAeJurT1+22PK+BMsXJdun40df17KhFlaBJ2NTazVttW5TXVRGd9ts3VOgFfptbqvhue7UwfApf4gzU37WtiwQDSPtNs8uqqFpP4NTAUZngpxIcazBKT9SYmphHxhV4c6CtRKZKrMOtwYWvf9UfK1GIBxhYjaUtxYiBi67BX9alkak7Kb2JWJVYwWXr27gvj0n897nzvA0ZELOoiGEqAR+BfyFlHJeKaNuIeS9H4UQ4jYhxF4hxF5fKEIgjXnCC3ns4BlWNVakHRASQnDtphZ+3z0Sy4jJlROjM1S5bLGgY7ZcvqaBl0+NMxtc/Lxi7UMWWBqFKvA7ENcra8+JxVvOz9VomGtpgNa4cLBATQvL1T0F2gzw+E4BhquqIO6pNAPhS0E0AG68bAWnxnw8m6bHIBui0fk1WumSk2gIIexogvFTKeWv9cWDumsJ/V/Df9MPdMRt3q4vW2x5e4LlZyGlvFNK2SWl7AIyrqicmA3y/LFRrtu0LKPMnJ2blhEMR3nmiDljYI+PzLC6sSLn7KAr1jQSikj2nli8OjxZEKzOY6fSacu7aOzvm0IIrePr3hSiMVejYf5I0ZYqV8EsjXJ1T8HZVeH5biFikG72lD8UXRLuKdAyNOs8dn724sm8HWNg0ocvFCmcaOiZTD8CDkkpvxn30YOAkQF1K/BA3PJb9Cyq7cCk7sZ6FLhWCFGnB8CvBR7VP5sSQmzXj3VL3L4W5bW+zLq9PvPGMOGojKXSpkuXnunwny+b43vsGc4+3TaeSzvrsFtFyqeU7mEvDqsl5o4yEEKwot6Tf9Hon2R1YwXbVtWnFLh8WxqFao9eblP74mmodM5L/Mh3NbiBy3buZE8ZOG1W/ujidh47OJi3jgXdSTwNqcjF0rgSuBm4Wgjxiv7zTuAfgLcLIY4C1+jvAR4GeoBu4AfApwCklGPAV4A9+s+X9WXo6/xQ3+YY8JtUJ2W1iHluj3R48fgYVU4bW9prM9rOahHccnknvz00xAsZFNQlwh+KMDDpyymeYeBx2Lioo47njy1+TseGvHQ2erAlaLuwot5D72h+C/wO9E9yQVsNXZ319IzMLJqJdnrCR5XLlpen9OYqF6MzwbNaZOQDbWpfeXW4NVjYHn0kz32nDFwZ1GksFfcUwA3bVhCOSn71Un4C4tmk20Ju2VN/kFIKKeUWKeWF+s/DUspRKeUOKeU6KeU1hgDoWVOfllKukVJeIKXcG7evu6SUa/Wfu+OW75VSbta3+YxMo1+3227N2NLY1zvOhStqM2raZXDbW1azvMbFV/779ZyCVlo78vRGvKbD5WsaONA/yeRsKOk6i/kzVzZ4ODXuy1sgbng6wJkpP5vbari0U8uw3tub3NoYmPSbnm5r0FztRMr8V4UHwhGCkWjZxjQaKhxMB8KxmKHxBNyQp1GvBm67NWXvqWhU4gtFyj7lNp61zZVsW1XPfS+mFxAPR6IZPfgcG/ZS57HHWsSky5KrCHc7rLwxOJ12vcaUP8SRwWkuWVmXeuUkx/v8zvUc6J/K6YmgZ9hIt81M9ZNx5dpGohJ2H09sbfhDEU6OzSY1TTvqPQTD0bwFiA1r8IK2Gi5or8Fhsywa1zg96TO9sM+gpUBjX8u1WaGBcXMx4hrD3gC1Hnveq9tddq331GLPjAE9JbfcK8IX8uFtKzgxOsvuFJ4MXzDCDXfu5qYfvJD2vruHvKxrrsr4nJacaHjsVsJRmXZP+pdPTiAldK2sz/qY793ayoUdtXzj0SPMZJlJdXzESLdNv9vkYlzYUYvbbk3qojoxOkNUkjTdLt9pt/v7JxECNrXV4LRZ2dJWw55F4hpmjnldSHOBWomUa7NCg/oFrUSGp/M3sS8et91KJCoJRZKLRrlP7UvGzs3LqHHb+dme5BXikajkz+97mb294+zpHWNiNr1atWzSbWEJiobh00x39Om+3nEsAi5ckVk8Ix6LRfD/vGcjw9MBvv/0saz2cXzES2Olk6oEMzyywWGzcOmq+qRFfkcHF/dnrtQL/PI1L/y1vklWNVbEbqBdnfUcHJhMWGfjD0UYnQnmJXMKoKW6MK1EynWWhkFj5fymhYVoIQJx7dEXSaVfqqLhslt5/8VtPHrgTMKYn5SSLz90kMdeH2TXha1IqcVoUzHqDTA+G8o4ngFLUDTsVguNlY604xr7esdYv6w65z/ki1fUsevCVn7w+x76sqikPjEym1MleCKuWNPAG4PehJlB3UNehEjePqC11o3VIvLWuNAIghtc2llHKCJ5te/s9if5zJwCzVcvClAVHhONMndPGTevQlSDQ5xoLFLgV+5T+xbjxm0rCEaiCUey/uD3PdzzfC+feNMqvvGBLbjslrS6XGcbBIclKBqg+cnTyaAKR6K8fHKCrs7s4hkL+fzO9QgBX3/kSMbb5tLdNhlXrGkASOii6h720lHnSRo4tFsttNa68pJ2awTB40XDiCklimuczmONBoDNaqGhwpl3S8NwT5XbfHADwz01FmdpFEI0YtP7FolTGqKx1CwNgPNaqrhkZR0/23NyXlznwVcH+LuHD/OuLcv563duwGmzcsnK1FmTkLi7dbosWdF4Y3A6ZUuRw2emmQ1Gsg6CL6S11s1tb17NQ68OsK83tYloMOUPMeINZDQXPB02tdZQ7bIlbClyLI1K0BV56nZrCPrmONGo9ThY11yZMINqIM+WBhRm7Ku3TOeDG1S7bNitghFvkJlAmJlgpDCi4Ug9vW+puqcMbty2gp7hmZjraXfPKH/181fZ1lnPP31wa2z+zuWrGzh8ZvqsYVkLOTroxeOwZvUgtjRFo72WqITXTy9ubezTb1BmiQbA//XWNbRUO/nyfx1KO131hBEEbzBXNKwWwfbVDTzXMz+uEYlKetIYvLKiviIv7ikj3rSptXre8q7Oevb1jhNZcN1Ox2aD58fSAGiuKoClUeYxDSGEXhUemKvRKEhMQ7tNLWppGKKxBN1TAO+6YDlVLhs/e/EkRwenue3evXTUu7nzlkvmeQu2r9a8Cy8kyZo0ODbsZU1TZVbdJ5akaGxp155gU8U19vWO01LtpM3EJ9gKp43/dd16Xj01wQOvJux6chZG5tRqky0N0FxUp8Z8827+p8ZmCYajKStBV9R7GJ0JmtZby8CoBF8Y9L+0s45pf5g3FsxIHpj001DhyGsOfku1i8E8p9xOB8o75Ra0Fumj3uBcC5ECxjQW8xwsZfcUaGL4/ovaePjAGT5y9x6cdis//ug2aj3za2S2tGtZk7t7Fvd0ZNNzymBJikZLtYvmKif70xCNrpX1pk6CA3jfRW1saa/h6785krJpIGiiIQRntfMwgyvXNgLzW6UbQbBU6XZGBpXZabcH+ifnuaYMjLTnhXGNfNZoGDRXORmdCWQ0X30hvuDizTK9/jB2q8BpK98/u4ZKByMzwYJaGu40sqf8S9zSAK1CPBiOMjEb5O6PXJpw7o/DZqGrc/G4hjcQ5vSkX4nGQra01/DaIsHw05M++id8prqmDCwWwZfevZEzU37+9ZmelOsfH5mhrdadlyfptc2VNFU5eS7uS5RuECxWq2HivPARb4DTk/OD4AYd9W6aq5xnxTXyWaNh0FztQsrs57EA3PiD3Xz6py8n/dxoVpjnAZR5pUF3TxWq7xSklz01u8QtDdBGwX7p3Rv58ce2JXzoMti+uoEjg9NJ2/IY3a0zGbwUz5IVjc1tNRwb9iYttstHPCOeSzvredcFy7nzdz0pi22O5yFzykAIwRVrGnju2Ggs86J7yEtTlZMa9+JZPMYwJjMzqPYnCILHn+ulnWc3LxyY9OUtc8qguSq3Ar8jZ6Z55dQEvz00GJuGtpBpf/k2KzTQmhZq7imLmMuoyidpZU8t8UC4wcfftIpLOxcvRL58jRHXSOyiMjwN61qUaMxjS3sNUsLBgcSV4XtPjOOyW9i4IBhrJp+5ei2+UIT7FqnmlFJy3KTutsm4Yk0Dw9OB2Jfl6JA3rbkh1S47tR67qRlUB3SX4aa2xNe9q7OO/gnNCgTt6XzaH85r5hTEFfhlGde4/5V+rBaB3Sr4yfO9CdeZLuNmhQb1FQ5mg1oLmoZKZ1b92jIlZmkskj11Lrin0uWCtho8juTdILqHvditgpVZusOXrGgYT7KvJSgWA3jp5Dhb22uxJ+jwahYblldz+eoG7n3uRFJf+ehMkOlAOM+iYcQ1NGsjnXRbA7NbpO/v1yrBq5NUvi+MaxQicwriWolk0WsrGpU88HI/b1nXyLu3tPLLfX0Jkwe8gRBVZZo5ZWBUhR8+M12QanBIv07DEO1zHbvVwqWd9Un7VXUPeelsqEjY3TodlqxoNFe5WF7jSthOZDYY5uDAlGlFfYvx0Ss7GZj085g+TnYhRuZUPkWjo95DR72b546NMDgVwBsIZyQaZqbdJguCG2xYXoXHYY25D40ajdY8WxqNlU69KjxzS2PPiTEGJv1cf1Ebt1y+Em8gzK8SzHcu51kaBvUVmlAcG/YWJJ4B4HJot6nFmpAaszTKOV5kJttXN3B0yJtwFkcmD42JWLKiAZqZliiD6pVTE0SiMqcmhemyY0MLHfVu7vrD8YSfG3PB8ykaAFesbuT5Y6OxdNZ0B6+sqPfQN+7LKavIYNQbYGDSzwVJXFOgVWdfvKIu1rywUJaG3WqhocKR1TCm+18ZwOOw8vaNLVy0oo6t7TXc8/yJs7qyest0Png8Rhv0UEQWJHMKwGG1IERq0VhKbdFzZS6uMd/aCIaj9I7NKtFIxgVtNfSMzDDlnz9T4iX9KfaiHJoUpovVIrj18k729o4nFLCekRnsVmFqrUgirljbwJQ/zAOvDADptw9Y2eAhHJWx/k+5sD/WDn3x697VWcfhM1NM+UMMTPoRYi7mkE+asxj7GghH+O/XBrhu0zI8Dk0Qbr2ik57hGf7QPb+ocilYGo0Vc0JRKEtDCKHNCU9Rp+F2LOnbWUZsbtX66S2Ma5wYnSESlUo0knGBXuR3sH9+MHxv7zjrmivPKozJF398aQcVDit3P3u2tXFiZIYV9Ymn55mJ8eTx0GsDVLlsaf/Bd9Sbl0FltA9JFgQ36FpZj5Ra2xVNCYQAABKPSURBVPrTEz6aq5x5jT0ZNFc7M45pPH1kmCl/mF0XtsaWvWvLchorHdzz3Il56077w2Vd2AdQHzdwqVCiAVpcI1VMY6lnTmWCzWrh0s66s+IaRnfrbNNtYamLhu47398/FwyPRiUv9Y4XJJ5hUO2y88GuDh56beAs94eWbmvO4KXFaK5ysa65UqsEb06/fcBKvbWJGaKRKghuYExR3HtijIFJX95rNAxasrA0Hniln8ZKB2/SiyhBm+9847YVPHF4KFYYGQxHCYSjZR8Ir3BYY8WJhRQNV4rpfb5QBLejvK+t2Vy+poFjwzPzujen6m6dDktaNBoqtRYh8e1Euoe9TPnDXLyicKIBmssiHJX82+6TsWXRqOT46AyrTBq8lAqjOjyTQfLLql3YrcKUtNsD/VOLBsENKp02Ni6vZs+JMU5P+GnNczW4QXO1kxFv4KzeV8mY8of47aEh3r2l9SxL8abLVmIVgp/sPgGU/wAmAyEEDXptRmOex7zG47Jb0giEL+nbWcYYfajiW6V3D3tpq3XnlJq85K/ylvaaeRlURuFYV4oCGbNZ1VjBVec38+8v9MZaTQxM+giGowWxNGDORZWJP9NqEXTU5Z5BNTYTpH/Ct2gQPJ6uzjpeOTVRUEujudpFVJK0knYhj+w/QzAc5fqL2s76bFmNi+s2L+M/9pxiNhiea1Zo0pCtYmLM1WgupHvKsbh7yh9S7qmFbGqtocppm9eHKpeeUwZLXjQ2t9XQOzrL5KwWDN/XO05DhYPOhsI83cfzsStXMeIN8tCrpwFt8BLkP3PK4E1rG9m5aRlv39iS0XYd9R56c2wlslgleCK6VtbjD0Xxh6J5T7c1mKsKT0807n+ln84GD1vbE/9OH7miM5Z8MG20RS9zSwPmMqiaKgtjAQK4bNZFLY3ZYEQV9i3AahFsWzVXrxGJSnqGvRl5GhKx5EXD6Hh7YEC7ae3rHePilXVFyee+cm0D57VUcvezx7VK8BEtKFUo0ahw2viXmy9hdYZfmpUNnpybFu7XiyzTFo24mFO+W4gYzI19TR0MPzPp5/meUXZd2Jb0u9S1so6Ny6u557kTsal95R4IB60q3GG1UO0u3O+SytLwBVXKbSIuX9PA8ZEZzkz66R/3EQhHs24fYrDkReOCtrk26cPTAU6MztKVp35TqRBC8JErVnFwYIo9J8bpGZnBbbfSUl04Mz8bVtR7mPKHY9baQh54pZ93/vPvk1aggmZpdDZ4UgbBDVqqXbGGifluIWKQiaXx4Kv9SElC15SB9v/dyeEz0zx5eAhYGpbGe7a08tE3dRb0wcuVIuXWH4rgUZbGWRhxjd09o3QP6zVayj21OLUeByvqPezvn+Clk/ltUpgO77uojVqPnbv+cDzWqLDUq1iNtNuFLqpIVPL3vznEn9/3Ct3DXm6560V+s/90wn2kGwSPx7A2CmVpGG0x0rE07n95gK0dtSmtxPde2Eqtx86/7db6UZV7nQbAVeub+eI7NhT0mC67lUA4RfaUsjTOYsPyaqpdNk00jLngTVU57XPJiwZo9Rqv9U2yr3cch9WS8c3LTNwOLR3zsdfP8OqpCdNHvOaDlQm63U75Q3zinj386zM93HTZCv7w+au4oK2GT/37S2fVJ8wFwTO77n/c1cF7t7YWrMeRw2ZUhS9uaRwdnOb101NcH1ebkQyX3cqHLu2Ite5eCu6pYuC2W5JaGlJKJRpJsFoEl61u4HldNBorndR4ckvGOCdEY0tbDX3jPn57aJDNbdVF933evH0lQgjGZ0OsMnnEaz7oqNMtDT2ucXxkhvd991l+d3SEr1y/ma+97wKaq1z89BOXcc2GFm5/8CDfeORwrI3GXCV4ZqKxfXUDd9x4UWz+cSFoqnLOy2tPhNHR9t1bUosGaP/fxq9QVeZdbovFYsV9gXAUKcGl3FMJ2b66gd7RWZ7tHmVtc+73m3NCNIybVc/wTMFTbRPRWutm5+ZlQOGC4LlQ4bTRWOnk1Ngsvz86zK7/7w+MzgT5yce3cfP2lbH1XHYr37/pYj582Qq+9/Qx/uoXrxGKROMqwYtn4aVLS7VrUUsjGpXc//IAb1rbmHZxW3udh2s2tOCwWmLzrhWZoRX3JRaNpT7qNVcu1+Ma/RO+nOMZACVvKwshdgL/DFiBH0op/yHTfcTfrIoZz4jnT9+yht3HRrm4RM4nFSvq3Tz2+iC/2NfH2qZKfnBLV2xIUzw2q4WvXb+ZZdUuvvn4G7GxoCsbPCmHPpUCzVVODp9JPIMFYN/JcfonfPzVdedltN+vXr+Z109PlXz8qlQxYhrPHRthTVMlzVXO2LU0LBAVCE/M+mVV1HrsTMyGck63hRIXDSGEFfgu8HagD9gjhHhQSvl6JvupcdtZ1VjB8ZGZgleCJ+OC9hr2fentxT6NtFnZUMFLJye4ZkML377hwkWzgIQQfHbHOpqrnPz1f+4nKrV+TOVAS7WLEW+QSFQmHDB0/8v9uO1Wrt24LKP9Nle7aC5A08WlipFJ9+EfvABo7UxWNVWwurEy9jBSbLdzqWKxCC5bVc+jBwdZ25xbEBxKXDSAbUC3lLIHQAhxH7ALyEg0QPPrue3WgvbLWUp86m1ruHx1Ax+4pD3tGMMN21bQVOXksz97mbee15TnMzSH5monkajkxh/sxpbg93zl1ATXbmqhYgmkzpYTf3RJO9vXNNAz7OX4yAw9wzP0jMzw8qlx+sa19vnLlCgn5W3nN/Pk4SHOX5a7aIiFPf9LCSHEB4CdUspP6O9vBi6TUn5mwXq3AbcBrFix4pLe3rPHbQbCEcIRqf7Yi0AoEsVmEWXhmukZ9vKlBw4QTJLeabUI/uadG2MdlBXFxx+KMOkLzXNZKeYTjUr6J3yx9PlECCH2SSm7Uu1rSdxBpZR3AncCdHV1JVRBp82K0oviUIi25maxuqmSn35ie7FPQ5EBLrtVuaZSYLGIRQUjo32Zspf80Q90xL1v15cpFAqFogiUumjsAdYJIVYJIRzADcCDRT4nhUKhOGcpaYeNlDIshPgM8Chayu1dUsqDRT4thUKhOGcpadEAkFI+DDxc7PNQKBQKRem7pxQKhUJRQijRUCgUCkXaKNFQKBQKRdoo0VAoFApF2pR0RXg2CCGmgSPFPo8SpxEYKfZJlDDq+qRGXaPUlNs1WimlTNnvp+Szp7LgSDql8OcyQoi96holR12f1KhrlJqleo2Ue0qhUCgUaaNEQ6FQKBRpsxRF485in0AZoK7R4qjrkxp1jVKzJK/RkguEKxQKhSJ/LEVLQ6FQKBR5Iu+iIYToEEI8JYR4XQhxUAjx5/ryeiHE40KIo/q/dfpyIYS4QwjRLYR4TQhxcdy+vi6EOKD/fGiRY96q7/eoEOLWBJ8/KIQ4sMj2O4UQR/Rz+ELc8t8LIV7RfwaEEPdne13i9lky10cI8bT+exu/Y3OS7S8RQuzXz+EOoU++EUJsFUI8r3/2kBCiOtfrU47XSAjhEUL8txDisH6+/xD32Z/q1+cVIcQfhBAbl+A1cggh7hRCvKFfgz9Ksn3C71Hc538phJBCiMZcr4++v3K8Rl8TQpwSQngXLF8phHhCP6+nhRDtuV6ftJFS5vUHWA5crL+uAt4ANgLfAL6gL/8C8HX99TuB3wAC2A68oC9/F/A4WppwBVrb9OoEx6sHevR/6/TXdXGfvx/4d+BAkvO1AseA1YADeBXYmGC9XwG3LKXrAzwNdKVxzi/qxxb6ubxDX74HeKv++mPAV5badyidawR4gKv01w7g93HXqDpuvfcCjyzBa/S3wFf11xagMZPvkf5ZB1p3695k258j12i7ft7eBct/Adyqv74a+IkZ1yidn7xbGlLK01LKl/TX08AhoA1t1vc9+mr3ANfrr3cB90qN3UCtEGI52n/u76SUYSnlDPAasDPBIa8DHpdSjkkpx9H+c3cCCCEqgc8BX13klGNzyaWUQcCYSx5Df4K+GsjZ0iil65MO+rGqpZS7pfaNvTfu3M4Dfqe/fhxI+PSUKeV2jaSUs1LKp/TXQeAltAFiSCmn4latAEwJKpbYNfoY8Pf6uUSllGcVuKX4HgF8C/hfmHR99HMpq2ukf7ZbSnk6wUcbgSf110+x4B6VTwoa0xBCdAIXAS8ALXEX4wzQor9uA07FbdanL3sV2Kmb/o3AVcyf6keK7QG+AvwTMLvIaS62vcH1wBMLbgA5UwLXB+Bu3XXypYXugrjt+5Jsf5C5L+8Hkxw/J8rkGsWfby3wHuCJuGWfFkIcQ3vC/exi22dDMa+R/vsCfEUI8ZIQ4hdCiJazN0/+PRJC7AL6pZSvpvHrZkWZXKPFeBXNawLwPqBKCNGQ4T6yomCioT/l/wr4i4U3W/1JY9EnCinlY2hzNZ4DfgY8D/9/e2cXYlUVxfHfP0d0+iBTiQpNRZJAssnEkDIlUkIoKHyJskYJm6KPh4xApUISQiM0EkKlVBIkQ+0hSPFBo0LMsUktS/PjqbAQC6XQSVcPe93meps7nTN3vu6d9YPN7Ls/ztp3zbl33X3WOWtxMYf8BmCsmW3NufT2eNTX0GX0tn6cx8zsNmCqlzk5588DnpXUTNr+X8g5v0OqTUeS6lzOO2Z2vGgdq8xsLPAKsDin/A7pAzqqI+2qvjKziT7/rRzrvxJYCLyaQ2Yuql1HzgJgmqRvgGmkNNh5z+VO0SNGQ9JA0j9po5lt8eZTvtUrbFV/9fayecHNbKmZNZjZDNJ1xiOS7lKbU/KhDuZPASZJOgl8AYxzB9LIovlNHcn3tQ4nXcL6tEK1/Esf0Q9mVvh7luT3mSxpQNH8JT52RJn5P5jZTDO7k/RhOla5dhJVpqMCq4GjZraizNvaxOWXZCqij+joNGknX5C/GZiY4zwaC4wBvvXP6ghgv6QbKlKOU2U6KouZ/Wxmj5jZHcAib/s9v0Y6gXWz04Sk0A3AipL25VzufFpmbU6mYufTXm8fAAzz+gTgEFDXjryhwAmS4+k6rw8tGTOa8o7wOpLDagxtjvDxRf1NwPpa04+/7+E+ZiDwMdBUZs2lDsxZ3n69tTn2NgDz+rGO3iB9OV1R0n5LUf1BYF8t6cj7NgH3eb0R2JznPCoZc5Kuc4RXnY6KjlXqCB9eOLeApcCSrtBRJj12uwC4h7TdOwC0eJkFDCNd5z0K7CxSpoBVpF+pB/E7VYDBwPde9gANHcicB/zkZW47/aMpYzS8fxbpzopjwKKSvl3AA7WmH5JTttnX8R2wEhhQZv4k/6AcA96l7SHRF11vR4A3C+39TUekX5RGcrQW1vuU9630uS0kB+b4WtKRt48i3RBxwGXfnOc8Khlzkq4zGtWoo2UkX8gl//u6t8/29R4B1gKDukJHWUo8ER4EQRBkJp4ID4IgCDITRiMIgiDITBiNIAiCIDNhNIIgCILMhNEIgiAIMhNGIwiCIMhMGI0gyICkRkk3Fb1eqy4Ka15G3sLuOnYQVEI8pxEEGZC0C1hgZvt6SN45M7u6J2QFQR5ipxHUPJJGSzosaY1S8p0dkuolNUjao5TIZqs8+U4782eTnl7e6HGB6j1u2STvPydpuR97p6TJ3n/cYxDhcYWWS/ra5T3t7TdK+tyPe0jSVKWkTfXettHHbZPU7DLmF60ti+xGSZ94+1FJr3WrwoPapqcePY8SpbcKKWzM33i4B+Aj4HFSCIdp3raEkphEJcfYRVHypeLXpNAUhSRLW4EdpNhUtwMt3j4fWOz1QcA+Unyzl/BQNaSYRtd4vTTWUCG0RT0p9MawHLIbgV9I4TIK8/832VaUKO2VugptThBUCyfMrMXrzaRoqkPMbLe3rSdFG+0MF4DPvH4QOG9mrZIOkgwWwExggu9aAK4FbiFlfXvfo69uK1pjKS9IetjrI33u6YyyISUDOg0gaQspDlOPXGoLaoswGkF/4XxR/SIwpNzATtBqZgXn4KWCLDO7pJRTA1Lwu+fNbHvpZEn3kiKqrpP0tpltKOmfDtwPTDGzP92/MjiHbPhvjohwZgadInwaQX/lD+CMpKn+eg6wu4PxZ0mJpTrLduAZ31EgaZykqySNAk6Z2RpStNKJPr61MJa0KznjBuNWUpjuvMyQNFRSPSmHx5cVvJegHxM7jaA/8yTwnlK2uOPA3A7GrvOxf5ESeuVlLely0X5JAn4jfXlPB16W1AqcA57w8auBA5L2k8JrN0k6DPxICsedl72k/B4jgA+th+4CC2qPuOU2CGocSY0kx/dzvb2WoPqJy1NBEARBZmKnEQRFSFoF3F3SvNLMPuiN9QRBXyOMRhAEQZCZuDwVBEEQZCaMRhAEQZCZMBpBEARBZsJoBEEQBJkJoxEEQRBk5h8QP/f3KJsNiAAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "dates = df.select(F.date_format('date','yyyy-MM-dd').alias('no_timestamp')).groupby('no_timestamp').count().sort(F.col('no_timestamp'))\n",
    "print(dates.show(dates.count()))\n",
    "dates.toPandas().plot(kind='line',x='no_timestamp',y='count')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Lets try a bar graph because I spent too long trying to figure out how this works"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<matplotlib.axes._subplots.AxesSubplot at 0x12217b128>"
      ]
     },
     "execution_count": 69,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAY0AAAE7CAYAAAAhNN25AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4yLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvOIA7rQAAIABJREFUeJzt3Xm8XHWZ5/HPk40EAmQdltxIaAyrzXongDTNEoGL2Aa7AVGWgEjsBkQduwXFaVrEaRj7xTo2Dg0BotgxoEJmCMQIiQ4gkA0JIULSIcuNLOlctkBCEvLMH7/fDYdKVd1zaz1V9X2/Xud1q37POb/6PVWn6rlnqVPm7oiIiKTRp94DEBGRxqGiISIiqaloiIhIaioaIiKSmoqGiIikpqIhIiKpqWiIiEhqKhoiIpKaioaIiKSmoiEiIqn1q/cAKm3EiBE+ZsyYeg9DRKShzJ8//z/dfWRP8zVd0RgzZgzz5s2r9zBERBqKma1MM592T4mISGoqGiIikpqKhoiIpNZ0xzRERHqyefNmOjs72bhxY72HUnMDBw6kra2N/v37l7S8ioaItJzOzk523nlnxowZg5nVezg14+6sW7eOzs5O9t5775L60O4pEWk5GzduZPjw4S1VMADMjOHDh5e1haWiISItqdUKRrdy81bREBFpMjfddBPvvfdeVfrWMQ0RqboxVz607faK606r40jyS46vEuqd40033cS5557LjjvuWPG+taUhIlIHU6ZM4eCDD+aQQw7hvPPOY8WKFZx44okcfPDBjB8/nlWrVgFwwQUXcP/9929bbvDgwQDMmTOH448/njPOOIP999+fc845B3fnlltu4U9/+hMnnHACJ5xwQsXHrS0NEZEaW7x4Mddeey1PPvkkI0aMoKuri4kTJ26bJk+ezOWXX84DDzxQtJ+FCxeyePFi9txzT4455hieeOIJLr/8cm644QZmz57NiBEjKj52bWmISF2NufKhbVOreOyxxzjzzDO3fagPGzaM3//+93zxi18E4LzzzuPxxx/vsZ9x48bR1tZGnz59OPTQQ1mxYkU1hw2oaIiIZFq/fv3YunUrAFu3bmXTpk3bYjvssMO223379mXLli1VH4+KhohIjZ144oncd999rFu3DoCuri4++clPMnXqVADuvfdejj32WCBcuXv+/PkATJ8+nc2bN/fY/84778w777xTlbHrmIaISI0ddNBBXHXVVRx33HH07duXww47jFtvvZULL7yQH/7wh4wcOZK77roLgIsvvpgJEyZwyCGH0NHRwU477dRj/5MmTaKjo4M999yT2bNnV3Ts5u4V7bDe2tvbXb+nIZItxU65rcfpuEuWLOGAAw6oyWNlUb78zWy+u7f3tKx2T4mISGoqGiIikpqKhoiIpKaiISItqdmO56ZVbt4qGiLScgYOHMi6detarnB0/57GwIEDS+5Dp9yKNKisXwQwy9ra2ujs7GTt2rX1HkrNdf9yX6lUNESk5fTv37/kX65rdSoaItJ0cq9jpS2xytExDRERSa3HomFmk83sdTN7PtE2zMxmmdnS+HdobDczu8XMlpnZc2Z2eGKZiXH+pWY2MdF+hJktisvcYvG3CAs9hoiI1E+aLY27gY6ctiuBR919LPBovA9wKjA2TpOA2yAUAOBq4EhgHHB1ogjcBlycWK6jh8cQaRmteNlwybYei4a7/w7oymmeANwTb98DnJ5on+LBU8AQM9sDOAWY5e5d7v4GMAvoiLFd3P0pD+e+TcnpK99jiIhInZR6IHw3d38l3n4V2C3eHgWsTszXGduKtXfmaS/2GCLSA52OK9VS9oHwuIVQ1W/I9PQYZjbJzOaZ2bxWPO9aRKRWSi0ar8VdS8S/r8f2NcDoxHxtsa1Ye1ue9mKPsR13v93d2929feTIkSWmJCIiPSm1aEwHus+Amgg8mGg/P55FdRTwVtzFNBM42cyGxgPgJwMzY+xtMzsqnjV1fk5f+R5DRETqpMdjGmb278DxwAgz6yScBXUdMM3MLgJWAmfF2WcAnwaWAe8BFwK4e5eZfR+YG+e7xt27D65fQjhDaxDwcJwo8hgiIlInPRYNd/9CgdD4PPM6cGmBfiYDk/O0zwM+kad9Xb7HEBGR+tE3wkVEJDUVDRERSU1FQ0REUlPREBGR1FQ0REQkNRUNERFJTUVDRERSU9EQEZHUVDRERCQ1FQ0REUlNRUNERFJT0RARkdRUNEREJDUVDRERSU1FQ0REUlPREBGR1FQ0REQkNRUNERFJTUVDRERSU9EQEZHUVDRERCQ1FQ0REUlNRUNERFJT0RARkdRUNEREJDUVDRERSU1FQ0REUlPREBGR1MoqGmb2DTNbbGbPm9m/m9lAM9vbzJ42s2Vm9nMzGxDn3SHeXxbjYxL9fDu2v2hmpyTaO2LbMjO7spyxiohI+UouGmY2CrgcaHf3TwB9gbOB64Eb3f3jwBvARXGRi4A3YvuNcT7M7MC43EFAB/CvZtbXzPoCPwJOBQ4EvhDnFRGROil391Q/YJCZ9QN2BF4BTgTuj/F7gNPj7QnxPjE+3swstk919/fd/WVgGTAuTsvcfbm7bwKmxnlFRKROSi4a7r4G+BdgFaFYvAXMB9509y1xtk5gVLw9Clgdl90S5x+ebM9ZplC7iIjUSTm7p4YS/vPfG9gT2Imwe6nmzGySmc0zs3lr166txxBERFpCObunPgW87O5r3X0z8EvgGGBI3F0F0AasibfXAKMBYnxXYF2yPWeZQu3bcffb3b3d3dtHjhxZRkoiIlJMOUVjFXCUme0Yj02MB14AZgNnxHkmAg/G29PjfWL8MXf32H52PLtqb2As8AwwFxgbz8YaQDhYPr2M8YqISJn69TxLfu7+tJndDywAtgALgduBh4CpZnZtbLszLnIn8BMzWwZ0EYoA7r7YzKYRCs4W4FJ3/wDAzC4DZhLOzJrs7otLHa+IiJSv5KIB4O5XA1fnNC8nnPmUO+9G4MwC/fwA+EGe9hnAjHLGKCIilaNvhIuISGoqGiIiklpZu6dEpHxjrnxo2+0V151Wx5G0huTzDXrOe0tbGiIikpqKhoiIpKaiISIiqaloiIhIaioaIiKSmoqGiIikpqIhIiKpqWiIiEhqKhoiIpKaioaIiKSmoiEiIqmpaIiISGoqGiIikpqKhoiIpKaiISIiqaloiIhIavoRJpEWox8hknJoS0NERFJT0RARkdRUNEREJDUVDRERSU1FQ0REUlPREBGR1FQ0REQkNRUNERFJrayiYWZDzOx+M/ujmS0xs6PNbJiZzTKzpfHv0DivmdktZrbMzJ4zs8MT/UyM8y81s4mJ9iPMbFFc5hYzs3LGKyIi5Sl3S+Nm4BF33x84BFgCXAk86u5jgUfjfYBTgbFxmgTcBmBmw4CrgSOBccDV3YUmznNxYrmOMscrIiJlKLlomNmuwF8CdwK4+yZ3fxOYANwTZ7sHOD3engBM8eApYIiZ7QGcAsxy9y53fwOYBXTE2C7u/pS7OzAl0ZeIiNRBOVsaewNrgbvMbKGZ3WFmOwG7ufsrcZ5Xgd3i7VHA6sTynbGtWHtnnnYREamTcopGP+Bw4DZ3Pwx4lw93RQEQtxC8jMdIxcwmmdk8M5u3du3aaj+ciEjLKqdodAKd7v50vH8/oYi8FnctEf++HuNrgNGJ5dtiW7H2tjzt23H329293d3bR44cWUZKIiJSTMlFw91fBVab2X6xaTzwAjAd6D4DaiLwYLw9HTg/nkV1FPBW3I01EzjZzIbGA+AnAzNj7G0zOyqeNXV+oi8REamDcn9P46vAvWY2AFgOXEgoRNPM7CJgJXBWnHcG8GlgGfBenBd37zKz7wNz43zXuHtXvH0JcDcwCHg4TiIiUidlFQ13fxZozxMan2deBy4t0M9kYHKe9nnAJ8oZo4iIVI6+ES4iIqmpaIiISGoqGiIikpqKhoiIpKaiISIiqaloiIhIaioaIiKSmoqGiIikVu43wkWkiYy58qGP3F9x3Wl1GolklbY0REQkNRUNERFJTUVDRERSU9EQEZHUVDRERCQ1FQ0REUlNRUNERFJT0RARkdT05T4RKZu+FNg6tKUhIiKpqWiIiEhqKhoiIpKaioaIiKSmA+EiIlWWPFGg0U8S0JaGiIikpqIhIiKpafeUiEik75v0TEVDRKQCmum4RTEqGtKUWuUNLLWjrZBAxzRERCS1souGmfU1s4Vm9n/j/b3N7GkzW2ZmPzezAbF9h3h/WYyPSfTx7dj+opmdkmjviG3LzOzKcscqIiLlqcTuqa8BS4Bd4v3rgRvdfaqZ/Ri4CLgt/n3D3T9uZmfH+T5vZgcCZwMHAXsCvzGzfWNfPwJOAjqBuWY23d1fqMCYpYVpN4NI6cra0jCzNuA04I5434ATgfvjLPcAp8fbE+J9Ynx8nH8CMNXd33f3l4FlwLg4LXP35e6+CZga5xURkTopd/fUTcC3gK3x/nDgTXffEu93AqPi7VHAaoAYfyvOv609Z5lC7dsxs0lmNs/M5q1du7bMlEREpJCSd0+Z2WeA1919vpkdX7kh9Z673w7cDtDe3u71HIvUjs6QEqm9co5pHAN81sw+DQwkHNO4GRhiZv3i1kQbsCbOvwYYDXSaWT9gV2Bdor1bcplC7SIiUgcl755y92+7e5u7jyEcyH7M3c8BZgNnxNkmAg/G29PjfWL8MXf32H52PLtqb2As8AwwFxgbz8YaEB9jeqnjFRGR8lXjy31XAFPN7FpgIXBnbL8T+ImZLQO6CEUAd19sZtOAF4AtwKXu/gGAmV0GzAT6ApPdfXEVxisiIilVpGi4+xxgTry9nHDmU+48G4EzCyz/A+AHedpnADMqMUYRESmfvhEuIiKpqWiIiEhqKhoiIpKaioaIiKSmoiEiIqmpaIiISGoqGiIikpp+ua+B6dpLIlJr2tIQEZHUVDRERCQ1FQ0REUlNxzR6oRV+JrQVchSR0mlLQ0REUlPREBGR1LR7KsO0q0hEskZbGiIikpqKhoiIpKaiISIiqaloiIhIaioaIiKSmoqGiIikplNuRURaSLmn8mtLQ0REUlPREBGR1FQ0REQkNRUNERFJTUVDRERS09lTIiJ1lDybqREuSlryloaZjTaz2Wb2gpktNrOvxfZhZjbLzJbGv0Nju5nZLWa2zMyeM7PDE31NjPMvNbOJifYjzGxRXOYWM7NykhURkfKUs3tqC/BNdz8QOAq41MwOBK4EHnX3scCj8T7AqcDYOE0CboNQZICrgSOBccDV3YUmznNxYrmOMsbbUsZc+dC2SUSkUkrePeXurwCvxNvvmNkSYBQwATg+znYPMAe4IrZPcXcHnjKzIWa2R5x3lrt3AZjZLKDDzOYAu7j7U7F9CnA68HCa8TXaJl+r0m+GiDSWihwIN7MxwGHA08BusaAAvArsFm+PAlYnFuuMbcXaO/O0i4hInZRdNMxsMPAL4Ovu/nYyFrcqvNzHSDGGSWY2z8zmrV27ttoPJyLSssoqGmbWn1Aw7nX3X8bm1+JuJ+Lf12P7GmB0YvG22FasvS1P+3bc/XZ3b3f39pEjR5aTkoiIFFHO2VMG3AkscfcbEqHpQPcZUBOBBxPt58ezqI4C3oq7sWYCJ5vZ0HgA/GRgZoy9bWZHxcc6P9GXiIjUQTnf0zgGOA9YZGbPxrbvANcB08zsImAlcFaMzQA+DSwD3gMuBHD3LjP7PjA3zndN90Fx4BLgbmAQ4QB4qoPg5Sj1ALoO6IpIKyjn7KnHgULfmxifZ34HLi3Q12Rgcp72ecAnSh2jiIhUli4jIiIiqekyIiIiDaheu8S1pSEiIqmpaIiISGoqGiIikpqKhoiIpKaiISIiqaloiIhIaioaIiKSmoqGiIikpi/3iVSArj0m1ZDFH5NT0agBfaCISLPQ7ikREUlNRUNERFJT0RARkdRUNEREJDUVDRERSU1FQ0REUlPREBGR1FQ0REQkNRUNERFJTd8Ib0FZvDSBiDQGbWmIiEhq2tIQkVR0DTUBFQ2pEH2giLQGFQ3JNB1/EckWHdMQEZHUVDRERCS1zO+eMrMO4GagL3CHu19X5yGJ9IqO90gzyXTRMLO+wI+Ak4BOYK6ZTXf3F+o7ssrRB4qINJJMFw1gHLDM3ZcDmNlUYALQNEWjkajASa3pRIjsyXrRGAWsTtzvBI4st1OtiLWlYiPVoPdxYdV8z5m7V6yzSjOzM4AOd/9yvH8ecKS7X5Yz3yRgUry7H/BivD0C+M8iD1Es3uyxrI1HOSpH5Vjf8ezl7iOLjC9w98xOwNHAzMT9bwPf7sXy80qNN3ssa+NRjspROWZrPIWmrJ9yOxcYa2Z7m9kA4Gxgep3HJCLSsjJ9TMPdt5jZZcBMwim3k919cZ2HJSLSsjJdNADcfQYwo8TFby8j3uyxejymcqx8rB6PqRwrH6vHY/Y0nrwyfSBcRESyJevHNEREJENUNEREJDUVDRERSU1Fo4mZ2X/p5fzDzGxYtcbTw2MfXqB9FzM7wsyGltDniPJHVjn5xmNmQ81sl3qMp1S9Xa8Syw2vwljyrjcplqvoelXsdczi+6ospXy5I4sT8EvgXGBwntgC4LvAPnli7cBs4KfAaGAW8BbhOyKHAYOBa4DFsX0t8BRwAbArcB3wR6ALWAcsiW1Dioz14SKxXwP/DPwE+GJO7C7gNsJFHIcD/wQsAqYBBwDDEtNwYAUwNOZVKIePAVNj21JgGfB6bBvTw3P+xzjf/wO+A/RPxH4DPAw8BOwD3A28CTwD/DVweGI6gnCJmMPi/CNiH6cAq2JfK4F3gDuA8cSTOBKPdyrwMvB47Gcx8B+x37OLjPMBYP8iY70qMW8b8GiMPRn/ljKes4Ap8bX4IOa4Kr6ew6n8OvUwsAuVX6/OSPSxK3An8BzwM+CWxOvYDiwnrFsrgZco7f34hSLrzeHAl4q8Vg9S+fWq2Ov4Z5TwvqL4e6qndbXY++qfijw3+/bqs7beH/aVmoA1wP2EN9o04HPAgBh7GfiX+II+A3wD2DPGnokrxhcI17k6I7aPB34fV7YL4hP934D/DowF7olvhCuA3RPj2D22/T7nBUy+kGuLxDYQPiBOJ3yR8RfADrHvt4CvAlcS3pxXEN5YXwU85pmcNse/7xbJoRP4PNA3kUNfwgftU3FFzDf9DbAJ+FvgUODWuAIOj32sB/4qPq8rY38W2zzOOzsxbYh/1yfG8STxDUa45MFG4DLgifh63wwcFePPEj7gjiZ80Ha3HwC8XWScC4HfFRnr24nxTCNcrqYPYf16t8TxvAMcH+//NXAjsBNwLWEdrPQ69QphPar0evV+Yox3xPHvRXh/vZWIzQb+a7y9L/A+pb0fi603jwELirxW1Vivir2Or1H4ffUipb2nelpXiz0/7xR5bh5t1aKxMP7dBTiP8N2OtYT/opYm5jsW+Ffg1fhkrkrEVuX2Cfwhp21u/NuHxJsmz3g8rsiz80zFYltz+rkqrszDgfeKjHUN8Ajw54m2l+PfYjlsKpLDUsIHxN3xecydPsiZ/1zCf2L75Ix1Wc58y4HfAqfmGetiYJd4+3GgT2KeDYnbHwO+RdiKXA68moitznm8DUXGuaB73Skw1mQezxaJlTOe+Ynb1VinNuQZeyXWq+SHdG7/G4F+8fZThfKnd+/HgutNivFsqMF6lXwdi72vnNLeUz2tq8XeV8Wem4WFxpp3/L2ZOctT8klJtA0nVO138sT6Ah2ETcaTgTMJlfv0GD8OmEeo3H8R2z7LR6+F9W5cwXZLtO1G+E9tPTC2wFg39xDrk9N2QVxxNiXars2Z5znClsR9wA3AzsDyGCuWw9vxTXsksGecjoxt04D5wCeKjHVgTtunCJvimxNtl+TM8zxht9+NcbwfS4z1rPiYXwKuJ/xHPDG+yV4rMI794xvmK8A/xOfiG4SrJE+Mr1Ohcb4CPFdkrFsIu1puJXyAJncXbChxPG8SPgxGEf6b/0Vczqq0Tq0m7OKq9HrVSdhy/WbM1xLLrSHsaj2RsLvmZsJ76nvAujLej3nXmzjP60Veq1VVWK+KvY7F3lddlPae6mldLfa+KvbcPJ9vLIWmun/YV2oCflckNrVI7BDCZUoejivJzXFlWAwcAxxM2GR+g/Afyr5xuZGEN/L1fLj/uYvw5rye8Ibcr8BjXl8k9kvgU3naOwibx/mO2XwcuD9xfwJh19Kr8X53Dm/GHPZL5PAN4O8I/00uitPDwCXADoT/BD9WYKw3AMflaT+M8JsnhcZ6U868s4HXc+a5HvgV8H8I+9tPAW4o8jqOBv53nHf3mNfzhH2//1xknLMIHwqFxjqT8AHRPQ2Nsd2Bp0scz4mEgvw8Yd/9HnGZ4cD5VVinTgf+ZxXWq6tzppGJ52YKcALwc8IWe/d69RXg5yW+Hz/Zw3ozkcKv1f+ownpV7HX8PIXfVydS2nuqp3W14Puqp+emUP75Jn0jvEmZ2SDCgcbn6z2WnpiZATu7+9v1HosUl6X1SutNcdV6fpqqaJjZ/oT/hkbFpjXAdHdfUmSZC939rt7GuuOEg5OjCPtt303EOghnmYwi/Ee6PifmhP8Ak2N90N0fMbNTahkrkt8/uvs1pcSzFgOeJp414u4rErEvufvk+PzkjROeq2rFfuPuK3Ni6wnrx/2E/0onELY8fgycUSR2EkVe41qvVxWOPeDuMykgi+sqH65z+V7jktabaq2r7j45Xx55c2uWomFmVxDOKJhK2NcK4Qk6m7B76roCy61y94/1NhbjXYSD7UsIZzt8zd0fjLHVwHsFYq8T9s9OyRnr+cAehH2XtYotdfevlZh/Sc9dHWJvAX8gHEj8K8Jm/K0xtoCwO+SYAvFXCaeI1iq2lnAwcwBhv/gOhLOdTgMOjMvli+1HkdeYUGj2LRCv9TrXCutqsXWu1HWjWuvqAndP/X2OZioaLwEHufvmnPYBhFPjXsy3GHAQYZ9kvti+BZZLLruLu683szGE//5+4u43m9kGwj7efLGN7j4wTw5GOHtmQA1jWwgHX/PlN4hQ+ArlP5jw3DZCrL+HS+0PIXyP4EV3/4aZLSRc7fmwAvENhE38msXcfZCZ9SecUbSHu28ys36EEzoKxd519x22Sz68xi8B7u77FojXep1rlXW10DpX6rpRrXV1obsfVuC525734gBIlifCJvpeedr3Iqxsh8bbyWkM4Us5hWJ/IpxvXSi+OeexBhMOfN3A9qfjfSRGPG89Z55xdYhtInGmTk58NeGsk0LxLQ0Sy32d+hK+iHYf4QDrkiLx92scS57++UjOfO8ViRV7jRcRzvzJyjrXCutqsXWu1HWjWuvq4nw5FJoy/3savfB14FEzW0pYgSCccvZxwjc/B7v7s7kLmdmKIrE5hJW4UHydmR3aHfOwVfEZYDIwsEhsAPC/zGxnPtwEH034ktWXaxybQiiCr23/lPIzwimAheLPNEhspZkd5+6/BXD3D4CLzOxawheqZhSJD6hx7AwzG+zu6929ozsBM9sd2FQk9h8Ufo0vIOyeui0j61wrrKvF1rlS141qrat/k2f8BTXN7ikAM+tD+I8keQBtbnyCqvF4bcAWd381T+x0wsHxfLFj3P2J+GbfNtbkvLWONTMLZ/zg7hvyxEYRTmstFN8H+FMNY6PcfU2e9p2Andz99WKxnl7jLK1zzbyu9rDOlbxuUJ11Ne86V1BvNksabQImVTpWrX5JXBsmy7GsjUc5KkflWJ1+Cy5XykKNMpHnW+LlxqrVb6PEsjYe5agclWN1+i00Nful0a0KsWr12yixejymcqx8rB6PqRwrH6tmv/kXihWnKZlZm7t3VjJWrX7NrI+7b816LGvjUY5FY+ZF3uDF4s0Qy9p4GinHokrZPGmUCXis0rFK9Eu8rn+i/VzCxcQmZSxmGRuPciwc+xwwLLaPJJxptIhw7ae2HuJfboKYciyj3159rvZm5ixPhPPQk9MiwnX7nyOcNltKLN9UiX6T5+J/lw8vincfiStuZiB2Ix+9pHK9x6McC8fWJWI/J1xYr41wuu0s4IUi8fVNEFOOZfTbq8/aen/YV2oiXE7hp4QrY+5F+PLd6nh7VomxvarU7/OJcS8gnC4J0J+PFpR6xxbx0ev313s8yrFwLPmDSNt+1yHef5bw7d9C8Y1NEFOOZfSbvN/T1DQHwt39s4Rr5N8OHOLhglyb3X2lu59UYmxlNfoF+pnZYWZ2BOGXvd6NOWwm7GrMSuwDYFCGxqMcC8feMbNrLHw/YI6ZfY6wwAmEL8bNKRLvaoKYciyv3/R6U2EaYSL83OINhJ9p7axErNL9sv0vqyWvw/92hmLzGmisrZ7jfMKPHXX/TvVWwnWRfka4MkL/IvE/a4KYciyj3958xjbt2VNmdghwtLv/uFKxavYb5+lL+N3m7S68lqVY1sajHD8aM7NdCT+1uq5AXgXjzRDL2ngaKcc0munaU91PRgeJyw+Y2RB3f7PUWLX6zRcj/AxrpmKF8s/iWJXjR2NmVjTHZLwZYsqxvH7TapotDTM7n/CTk78mvJEgnB1wEuGChZ8qIfa9eL/S/TZKrBXyV47ZGqtyrH2O33P3KaTVm31ZWZ4Iv3sxJE/7UMIllUuJvVSlfhsl1gr5K8dsjVU51j7Hl3Lbi03NtHvKCJd/ztX9bdlSYtZDvNljrZC/cmyOmHIsv99Ummn31ETgHwmbX8nf0zgJeIzwe8q9jX2f8ERXut9GibVC/soxW2NVjrXP8fvufjcpNU3RADCzocApbH+Q8I1SY9Xqt1FirZC/cszWWJVj7XOkN3qzL6vRJuAzlY5Vq99GiWVtPMpROSrH6vRbcLlSFmqUiQa6fn2jxLI2HuWoHJWjfk+jkhrp+vWNEqvHYyrHysfq8ZjKsfKxavabXymVplEmYFylY9Xqt1FiWRuPclSOyrE6/RaamumUW8xsMOEbj6MJF6J7yeKP1JQaq1a/jRJrhfyVY7bGqhxrnyO90DRnT5nZWcDfE36v4gTgSaAP8OfAPcDnS4idAxxQhX4bJdYK+SvHbI1VOdY+x3PcfRFplbJ5ksUpPhk7xtsjCKeSARwMvFti7Mkq9dsosVbIXzlma6zKsfY5Ptmrz9pqfpDXciL8mE7UhcU/AAAGH0lEQVT3ltMgPvrDOhtLjD1fpX4bJdYK+SvHbI1VOdY+x20/CpdmaqZjGjOAR8zsd4T9dvcBmNkwYH2JMQMeqkK/jRJrhfyVY7bGqhxrn2OvzqJqmmMaAGb2aeBA4A/uPiu29SH8cMn4UmLu/n41+m2UWCvkrxyzNVblWPsc3f19UmqqogFgZruR+Jq8u79Wbqxa/TZKLGvjUY7KUTlWp980mqZomNmhwI+BXfno9eLfBG4Cvl5C7BLCVSAr3W+jxFohf+WYrbEqx9rneIm7LyCt3hwAyfIEPAscmaf9KGBDibE/VKnfRom1Qv7KMVtjVY61z/EPue3Fpmba0ljq7mMLxDa5+4ASYssAr0K/jRJrhfyVY7bGqhxrn+Myd/94vlje+ZuoaNwC7ANM4cPrxY8GzidshnWWEHuZsDlY6X4bJdYK+SvHbI1VOdY+x5fd/TJSapqiAWBmpwIT+Oj14qe7+4xSY9Xqt1FirZC/cszWWJVj7XOkF5qqaIiISJX15gBIlifCWQHXAUuALmBdvH0d4WcNS4kNqVK/jRJrhfyVY7bGqhxrn+OQ3nzW9qF5TAPeAE5w92HuPpxwYa43gQUlxqZVqd9GibVC/soxW2NVjrXPcRq90DS7p8zsRXffr0Cs1LMKXgSoQr+NEmuF/JVjtsaqHGufY8HPznyaaUtjpZl9y8I3HoHw7UczuwJ4p8TY6ir12yixVshfOWZrrMqx9jl2n02VSjMVjc8Dw4HfmtkbZtYFzAGGAe0lxs6qUr+NEmuF/JVjtsaqHGuf41n0hmfgIHalJmB/4FPA4Jz2jlJj1eq3UWKtkL9yzNZYlWPtc0ze72mq+gd5rSbgcuBF4AFgBTAhEVtdYmxBlfptlFgr5K8cszVW5Vj7HBf06rO2mh/ktZwIP04yON4eA8wDvhbvbygxtrBK/TZKrBXyV47ZGqtyrH2O236QKdVnbTU/yGs5AYtz7g8GHgFuADaUGHu2Sv02SqwV8leO2Rqrcqx9js8mYz1NVf8wr9UEPAYcmtPWj3CtFS8x9kGV+m2UWCvkrxyzNVblWPscP0i29zRV/cO8VhPhgly7F4idXmLsmCr12yixVshfOWZrrMqx9jkek6+90NQ0X+4TEZHqa6bvaYiISJWpaIiISGoqGiIikpqKhkgKZnaBme2ZuH+HmR1Yxcf7TrX6FimHDoSLpGBmc4C/d/d5NXq89e4+uBaPJdIb2tKQpmdmY8xsiZn9m5ktNrNfm9kgMzvUzJ4ys+fM7FdmNrTA8mcQLvh2r5k9G5edY2btMb7ezH4Y+/6NmY2L8eVm9tk4T984z9z4eF+J7XuY2e9iv8+b2bFmdh0wKLbdG+d7wMzmx8eYlBhbmse+wMwejO1Lzezqqj7h0tx6c36uJk2NOBEum7CF+OUmwo/OnAs8BxwX264BbirSxxygPd99whenTo23fwX8GugPHEL8ti0wCfhuvL0D4TIOewPfBK6K7X2BnePt9TmPPyz+HQQ8DwzvxWNfALxCuMpp9/LtPT1vmjTlm/qVWXNEGsXL7v5svD0f2IfwM5e/jW33APeV2PcmwiUZIFwb6H1332xmiwgFC+Bk4OC41QLhZzvHAnOByWbWH3ggMcZcl5vZ5+Lt0XHZdSkfG2CWu68DMLNfAn9BKFwivaKiIa3i/cTtDwi/t1wpm929++Dg1u7HcvetZtb9HjPgq+4+M3dhM/tL4DTgbjO7wd2n5MSPJ1zS+mh3fy8eXxnYi8eGsEVCkfsiqeiYhrSqt4A3zOzYeP884LdF5n8H2LmMx5sJ/F3cosDM9jWzncxsL+A1d/834A7g8Dj/5u55CVslb8SCsT9wVAmPf5KZDTOzQYRLSjxRRi7SwrSlIa1sIvBjM9sRWA5cWGTeu+O8G4CjS3isOwi7ixaYmQFrCR/exwP/YGabgfXA+XH+24HnzGwB8CXgb81sCeE3EZ4q4fGfAX5BuHbRT71GZ4FJ89EptyJNzswuIBz4vqzeY5HGp91TIiKSmrY0RBLM7EeES1An3ezud9VjPCJZo6IhIiKpafeUiIikpqIhIiKpqWiIiEhqKhoiIpKaioaIiKT2/wHGmpRNLtYz9gAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "dates.toPandas().plot(kind='bar',x='no_timestamp')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Prepare Tweets for OLDA"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Remove stopwords "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "more_then_3_charachters = [word for word in cv_tmp_model.vocabulary if len(word) <= 3]\n",
    "contains_digits = [word for word in cv_tmp_model.vocabulary if any(char.isdigit() for char in word)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "metadata": {},
   "outputs": [],
   "source": [
    "tokenizer = Tokenizer(inputCol=\"tweet\", outputCol=\"words\")\n",
    "prep_df = tokenizer.transform(df)\n",
    "cv_prep = CountVectorizer(inputCol=\"words\", outputCol=\"prep\")\n",
    "cv_model = cv_prep.fit(prep_df)\n",
    "ready_df = cv_model.transform(prep_df)\n",
    "# stopWords = [word for word in cv_prep.vocabulary if any(char.isdigit() for char in word)]\n",
    "# remover = StopWordsRemover(inputCol=\"words\", outputCol=\"filtered\", stopWords = stopwords)\n",
    "# prep_df = remover.transform(prep_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "metadata": {},
   "outputs": [
    {
     "ename": "Py4JJavaError",
     "evalue": "An error occurred while calling o819.collectToPython.\n: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 207.0 failed 1 times, most recent failure: Lost task 3.0 in stage 207.0 (TID 10013, localhost, executor driver): java.lang.OutOfMemoryError: Java heap space\n\tat java.util.Arrays.copyOf(Arrays.java:3236)\n\tat java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)\n\tat java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)\n\tat java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)\n\tat org.apache.spark.util.ByteBufferOutputStream.write(ByteBufferOutputStream.scala:41)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)\n\tat java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)\n\tat org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:43)\n\tat org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:456)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\nDriver stacktrace:\n\tat org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1891)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1879)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1878)\n\tat scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)\n\tat org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1878)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)\n\tat scala.Option.foreach(Option.scala:257)\n\tat org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:927)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2112)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2061)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2050)\n\tat org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)\n\tat org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:990)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)\n\tat org.apache.spark.rdd.RDD.withScope(RDD.scala:385)\n\tat org.apache.spark.rdd.RDD.collect(RDD.scala:989)\n\tat org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:299)\n\tat org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:3263)\n\tat org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:3260)\n\tat org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)\n\tat org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)\n\tat org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)\n\tat org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)\n\tat org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)\n\tat org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3260)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.OutOfMemoryError: Java heap space\n\tat java.util.Arrays.copyOf(Arrays.java:3236)\n\tat java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)\n\tat java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)\n\tat java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)\n\tat org.apache.spark.util.ByteBufferOutputStream.write(ByteBufferOutputStream.scala:41)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)\n\tat java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)\n\tat org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:43)\n\tat org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:456)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\t... 1 more\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mPy4JJavaError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-93-bc34afa90b31>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mpand\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mready_df\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtoPandas\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpand\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/dataframe.py\u001b[0m in \u001b[0;36mtoPandas\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   2148\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2149\u001b[0m         \u001b[0;31m# Below is toPandas without Arrow optimization.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2150\u001b[0;31m         \u001b[0mpdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mDataFrame\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_records\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcollect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcolumns\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcolumns\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2151\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2152\u001b[0m         \u001b[0mdtype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m{\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/dataframe.py\u001b[0m in \u001b[0;36mcollect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    532\u001b[0m         \"\"\"\n\u001b[1;32m    533\u001b[0m         \u001b[0;32mwith\u001b[0m \u001b[0mSCCallSiteSync\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sc\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mcss\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 534\u001b[0;31m             \u001b[0msock_info\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jdf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcollectToPython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    535\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mlist\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_load_from_socket\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msock_info\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mBatchedSerializer\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mPickleSerializer\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    536\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36m__call__\u001b[0;34m(self, *args)\u001b[0m\n\u001b[1;32m   1255\u001b[0m         \u001b[0manswer\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgateway_client\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend_command\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcommand\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1256\u001b[0m         return_value = get_return_value(\n\u001b[0;32m-> 1257\u001b[0;31m             answer, self.gateway_client, self.target_id, self.name)\n\u001b[0m\u001b[1;32m   1258\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1259\u001b[0m         \u001b[0;32mfor\u001b[0m \u001b[0mtemp_arg\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mtemp_args\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/utils.py\u001b[0m in \u001b[0;36mdeco\u001b[0;34m(*a, **kw)\u001b[0m\n\u001b[1;32m     61\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mdeco\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkw\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 63\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0ma\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkw\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     64\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mpy4j\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprotocol\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPy4JJavaError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     65\u001b[0m             \u001b[0ms\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjava_exception\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtoString\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py\u001b[0m in \u001b[0;36mget_return_value\u001b[0;34m(answer, gateway_client, target_id, name)\u001b[0m\n\u001b[1;32m    326\u001b[0m                 raise Py4JJavaError(\n\u001b[1;32m    327\u001b[0m                     \u001b[0;34m\"An error occurred while calling {0}{1}{2}.\\n\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 328\u001b[0;31m                     format(target_id, \".\", name), value)\n\u001b[0m\u001b[1;32m    329\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    330\u001b[0m                 raise Py4JError(\n",
      "\u001b[0;31mPy4JJavaError\u001b[0m: An error occurred while calling o819.collectToPython.\n: org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 207.0 failed 1 times, most recent failure: Lost task 3.0 in stage 207.0 (TID 10013, localhost, executor driver): java.lang.OutOfMemoryError: Java heap space\n\tat java.util.Arrays.copyOf(Arrays.java:3236)\n\tat java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)\n\tat java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)\n\tat java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)\n\tat org.apache.spark.util.ByteBufferOutputStream.write(ByteBufferOutputStream.scala:41)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)\n\tat java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)\n\tat org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:43)\n\tat org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:456)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n\nDriver stacktrace:\n\tat org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1891)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1879)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1878)\n\tat scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)\n\tat org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1878)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)\n\tat org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:927)\n\tat scala.Option.foreach(Option.scala:257)\n\tat org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:927)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2112)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2061)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2050)\n\tat org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)\n\tat org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:990)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)\n\tat org.apache.spark.rdd.RDD.withScope(RDD.scala:385)\n\tat org.apache.spark.rdd.RDD.collect(RDD.scala:989)\n\tat org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:299)\n\tat org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:3263)\n\tat org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:3260)\n\tat org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)\n\tat org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)\n\tat org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)\n\tat org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)\n\tat org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)\n\tat org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3260)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:498)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.GatewayConnection.run(GatewayConnection.java:238)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.OutOfMemoryError: Java heap space\n\tat java.util.Arrays.copyOf(Arrays.java:3236)\n\tat java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)\n\tat java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)\n\tat java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)\n\tat org.apache.spark.util.ByteBufferOutputStream.write(ByteBufferOutputStream.scala:41)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)\n\tat java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)\n\tat java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1189)\n\tat java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)\n\tat org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:43)\n\tat org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)\n\tat org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:456)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\t... 1 more\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception happened during processing of request from ('127.0.0.1', 58924)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py\", line 316, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py\", line 347, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py\", line 360, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socketserver.py\", line 720, in __init__\n",
      "    self.handle()\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/pyspark/accumulators.py\", line 269, in handle\n",
      "    poll(accum_updates)\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/pyspark/accumulators.py\", line 241, in poll\n",
      "    if func():\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/pyspark/accumulators.py\", line 245, in accum_updates\n",
      "    num_updates = read_int(self.rfile)\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/pyspark/serializers.py\", line 724, in read_int\n",
      "    raise EOFError\n",
      "EOFError\n",
      "----------------------------------------\n"
     ]
    }
   ],
   "source": [
    "pand = ready_df.toPandas()\n",
    "print(pand)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Exception while sending command.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1152, in send_command\n",
      "    answer = smart_decode(self.stream.readline()[:-1])\n",
      "  File \"/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py\", line 589, in readinto\n",
      "    return self._sock.recv_into(b)\n",
      "ConnectionResetError: [Errno 54] Connection reset by peer\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 985, in send_command\n",
      "    response = connection.send_command(command)\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1164, in send_command\n",
      "    \"Error while receiving\", e, proto.ERROR_ON_RECEIVE)\n",
      "py4j.protocol.Py4JNetworkError: Error while receiving\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n",
      "ERROR:py4j.java_gateway:An error occurred while trying to connect to the Java server (127.0.0.1:65022)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 929, in _get_connection\n",
      "    connection = self.deque.pop()\n",
      "IndexError: pop from an empty deque\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\", line 1067, in start\n",
      "    self.socket.connect((self.address, self.port))\n",
      "ConnectionRefusedError: [Errno 61] Connection refused\n"
     ]
    },
    {
     "ename": "Py4JNetworkError",
     "evalue": "An error occurred while trying to connect to the Java server (127.0.0.1:65022)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mIndexError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36m_get_connection\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    928\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 929\u001b[0;31m             \u001b[0mconnection\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdeque\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpop\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    930\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mIndexError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mIndexError\u001b[0m: pop from an empty deque",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mConnectionRefusedError\u001b[0m                    Traceback (most recent call last)",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36mstart\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1066\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1067\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msocket\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconnect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0maddress\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mport\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1068\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstream\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msocket\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmakefile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"rb\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mConnectionRefusedError\u001b[0m: [Errno 61] Connection refused",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mPy4JNetworkError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-94-4491b30c972f>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mtrainable\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mready_df\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mselect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'tweet_id'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'prep'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrdd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;32mlambda\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0mVectors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfromML\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcache\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;31m# print(trainable.take(10))\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mLDA\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrainable\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mk\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mseed\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moptimizer\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"online\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0mexit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;31m#Print the topics in the model\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/dataframe.py\u001b[0m in \u001b[0;36mselect\u001b[0;34m(self, *cols)\u001b[0m\n\u001b[1;32m   1322\u001b[0m         \u001b[0;34m[\u001b[0m\u001b[0mRow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34mu'Alice'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mage\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m12\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mRow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34mu'Bob'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mage\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m15\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1323\u001b[0m         \"\"\"\n\u001b[0;32m-> 1324\u001b[0;31m         \u001b[0mjdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jdf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mselect\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jcols\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1325\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mDataFrame\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjdf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msql_ctx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1326\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/dataframe.py\u001b[0m in \u001b[0;36m_jcols\u001b[0;34m(self, *cols)\u001b[0m\n\u001b[1;32m   1116\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m1\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlist\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1117\u001b[0m             \u001b[0mcols\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcols\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1118\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jseq\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_to_java_column\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1119\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1120\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_sort_cols\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcols\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/dataframe.py\u001b[0m in \u001b[0;36m_jseq\u001b[0;34m(self, cols, converter)\u001b[0m\n\u001b[1;32m   1103\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_jseq\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcols\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconverter\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1104\u001b[0m         \u001b[0;34m\"\"\"Return a JVM Seq of Columns from a list of Column or names\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1105\u001b[0;31m         \u001b[0;32mreturn\u001b[0m \u001b[0m_to_seq\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msql_ctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_sc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcols\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconverter\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1106\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1107\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_jmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mjm\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/column.py\u001b[0m in \u001b[0;36m_to_seq\u001b[0;34m(sc, cols, converter)\u001b[0m\n\u001b[1;32m     63\u001b[0m     \"\"\"\n\u001b[1;32m     64\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mconverter\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 65\u001b[0;31m         \u001b[0mcols\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mconverter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mc\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mc\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mcols\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     66\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0msc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jvm\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPythonUtils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtoSeq\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     67\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/column.py\u001b[0m in \u001b[0;36m<listcomp>\u001b[0;34m(.0)\u001b[0m\n\u001b[1;32m     63\u001b[0m     \"\"\"\n\u001b[1;32m     64\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mconverter\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 65\u001b[0;31m         \u001b[0mcols\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0mconverter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mc\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mc\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mcols\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     66\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0msc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jvm\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPythonUtils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtoSeq\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcols\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     67\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/column.py\u001b[0m in \u001b[0;36m_to_java_column\u001b[0;34m(col)\u001b[0m\n\u001b[1;32m     45\u001b[0m         \u001b[0mjcol\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcol\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jc\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     46\u001b[0m     \u001b[0;32melif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcol\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbasestring\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 47\u001b[0;31m         \u001b[0mjcol\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_create_column_from_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcol\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     48\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     49\u001b[0m         raise TypeError(\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/pyspark/sql/column.py\u001b[0m in \u001b[0;36m_create_column_from_name\u001b[0;34m(name)\u001b[0m\n\u001b[1;32m     38\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0m_create_column_from_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     39\u001b[0m     \u001b[0msc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_active_spark_context\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 40\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0msc\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jvm\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfunctions\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcol\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     41\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     42\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36m__getattr__\u001b[0;34m(self, name)\u001b[0m\n\u001b[1;32m   1647\u001b[0m             \u001b[0mproto\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mREFLECTION_COMMAND_NAME\u001b[0m \u001b[0;34m+\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1648\u001b[0m             \u001b[0mproto\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mREFL_GET_UNKNOWN_SUB_COMMAND_NAME\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mname\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m\"\\n\"\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_id\u001b[0m \u001b[0;34m+\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1649\u001b[0;31m             \"\\n\" + proto.END_COMMAND_PART)\n\u001b[0m\u001b[1;32m   1650\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0manswer\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0mproto\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSUCCESS_PACKAGE\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1651\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mJavaPackage\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_gateway_client\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mjvm_id\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36msend_command\u001b[0;34m(self, command, retry, binary)\u001b[0m\n\u001b[1;32m    981\u001b[0m          \u001b[0;32mif\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m`\u001b[0m\u001b[0mbinary\u001b[0m\u001b[0;31m`\u001b[0m \u001b[0;32mis\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m`\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;31m`\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    982\u001b[0m         \"\"\"\n\u001b[0;32m--> 983\u001b[0;31m         \u001b[0mconnection\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_get_connection\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    984\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    985\u001b[0m             \u001b[0mresponse\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconnection\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msend_command\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcommand\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36m_get_connection\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    929\u001b[0m             \u001b[0mconnection\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdeque\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpop\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    930\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mIndexError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 931\u001b[0;31m             \u001b[0mconnection\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_create_connection\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    932\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mconnection\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    933\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36m_create_connection\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    935\u001b[0m         connection = GatewayConnection(\n\u001b[1;32m    936\u001b[0m             self.gateway_parameters, self.gateway_property)\n\u001b[0;32m--> 937\u001b[0;31m         \u001b[0mconnection\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstart\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    938\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mconnection\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    939\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/opt/apache-spark/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py\u001b[0m in \u001b[0;36mstart\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1077\u001b[0m                 \u001b[0;34m\"server ({0}:{1})\"\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0maddress\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mport\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1078\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexception\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1079\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mPy4JNetworkError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmsg\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1080\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1081\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_authenticate_connection\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mPy4JNetworkError\u001b[0m: An error occurred while trying to connect to the Java server (127.0.0.1:65022)"
     ]
    }
   ],
   "source": [
    "trainable = ready_df.select('tweet_id', 'prep').rdd.map(lambda x,y: [x,Vectors.fromML(y)]).cache()\n",
    "# print(trainable.take(10))\n",
    "model = LDA.train(trainable, k=5, seed=1, optimizer=\"online\")\n",
    "exit(0)\n",
    "#Print the topics in the model\n",
    "topics = model.describeTopics(maxTermsPerTopic = 15)\n",
    "for x, topic in enumerate(topics):\n",
    "    print('topic nr: ' + str(x))\n",
    "    words = topic[0]\n",
    "    weights = topic[1]\n",
    "    for n in range(len(words)):\n",
    "        print(cv_prep.vocabulary[words[n]] + ' ' + str(weights[n]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
